### ISSUE TITLE
Could Sonnet support DepthwiseConv1D in future release?

### ISSUE THREAD

**Issue by mingyr** [deepmind/sonnet#100]
Dear Deepminder:

Is it possible in future release a DepthwiseConv1D method is provided? Since I mainly process one dimensional data, so it would be nice and convenient to have such an method for consistent implementation at my side.

Thanks a lot.

**Comment by malcolmreynolds** [comment]
Thanks for your suggestion, we will endeavour to support this at some point.

**Comment by mingyr** [comment]
Glad to know that, in that case I will close this thread.
