### ISSUE TITLE
Best way to use pre-trained nets in Sonnet

### ISSUE THREAD

**Issue by ferreirafabio** [deepmind/sonnet#107]
Hi,

I'm trying to use a pre-trained ResNet-50 as a module in Sonnet.

I have read the Sonnet documentation stating: `If you create variables yourself, it is crucial to create them with tf.get_variable. Calling the tf.Variable constructor directly will only work the first time the module is connected, but on the second call you will receive an error message “Trainable variable created when calling a template after the first time”.`

What is the best way to use a pre-trained network with Sonnet? I tried implementing it in the following way:
```
from keras.applications.resnet50 import ResNet50
class ResNet50Encoder(snt.AbstractModule):
    def __init__(self, name='resnet50encoder'):
        super(ResNet50Encoder, self).__init__(name=name)

    def _build(self, inputs, is_training=True):
        input_rgb = inputs[..., :3]
        base_model = ResNet50(weights='imagenet', pooling=max, include_top=False, input_shape=(120, 160, 3))
        base_model.layers.pop()
        for layer in base_model.layers:
            layer.trainable = False
        last = base_model.layers[-1].output  # pool 5 output
        last = Flatten()(last)
        output = Dense(512, activation='relu')(last)

        finetuned_model = Model(inputs=base_model.input, outputs=output)
        x = preprocess_input(input_rgb) 
        features_rgb = finetuned_model(x)
        outputs = snt.Linear(output_size=EncodeProcessDecode.n_neurons)(features_rgb)
        return outputs
```

Running it yields the following error:

> resnet50encoder_nodes/bn_conv1/moving_mean/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

Surrounding the ResNet creation with `tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE)` doesn't help either.

There seem to be a few issues with the batch normalization(bn) layer used in many pre-trained Keras nets w.r.t. variable scopes (see: keras-team/keras#9214). Due to this, I tried using VGG16 which does not use bn layers but exchanging ResNet50 with VGG16 in the above code then yields:

> ValueError: Trainable variable created when calling a template after the first time, perhaps you used tf.Variable when you meant tf.get_variable

The question that remains to be answered therefore is: what's the best way to use pre-trained nets in Sonnet and avoid the clash with tf.get_variable usage? The documentation doesn't seem to explain this.
Thank you

**Comment by malcolmreynolds** [comment]
Combining Sonnet with models defined in other systems such as Keras  or Slim will produce some issues as related to variable sharing. You may be able to get it to work by constructing the ResNet50 inside the constructor, inside a `with _enter_variable_scope():` block, but even then I think you would need to be careful that your top level module (ie ResNet50 Encoder) is not constructed multiple times.

To clarify, this is unlikely to work:

```python
class MyModule(snt.AbstractModule):
  # ...
  def _build(self, inputs):
    encoder = ResNet50Encoder()
    return encoder(inputs)
```

This _might_, assuming MyModule is the top level of your module stack:

```python
class MyModule(snt.AbstractModule):
  def __init__(self, name='my_module'):
    super(MyModule, self).__init__(name=name)
    with self._enter_variable_scope():
      self._encoder = Resnet50Encoder()
  
  def _build(self, inputs):
    return self._encoder(inputs)
```

It's hard to give definitive answers without looking hrough how the Keras model (and everything it depends on) is implemented.. but in general, mixing libraries is tricky. If you have a pretrained model in a specific library, you will probably get on best working entirely within that library. Sonnet is built on top of `tf.make_template`, which supports transparent reuse for anything that calls `tf.get_variable`. Our `_build` methods are wrapped by a `make_template`, under the hood. Anything calling `tf.Variable` directly breaks this assumption, and will lead to the kind of errors you are seeing.

If you have a pretrained checkpoint for a sonnet module, you can load that with a `tf.Saver` as normal. If you have a checkpoint for a module which you now want to connect as part of a larger graph, you can make a saver which refers to just a subpart of the graph using `snt.get_saver`, or in general passing a dict to `tf.Saver` to perform rewrites mapping between graph names and checkpoint names (you're probably going to want to remove some prefix from the graph names to make them line up with the checkpoint names).
