### ISSUE TITLE
Is there any easy way to duplicate module?

### ISSUE THREAD

**Issue by mingyr** [deepmind/sonnet#113]
Dear deepminder:

Recently I began to learn reinforcement learning. I am trying to convert the dqn in this same repo originally implemented in Lua to a TensorFlow version. I am a newbie to reinforcement learning, but it still seems to me that, the update of the Q network and the so-called target network are not synchronized however they share the same weights. I just wonder, is there an easy way to duplicate a module periodically? Then I can keep the target network which is a duplication fixed for some time while still have the Q network updating.

I am not sure I am in the right track or not. Please feel free to give any suggestion.

**Comment by tomhennigan** [comment]
Hi @mingyr, apologies for the delay getting back to you. Your code looks familiar to a bunch of code I've seen internally.

A slightly more concise way of achieving this copy operation can be seen below, the output of the program should be a where both values are the same:

```python
import sonnet as snt
import tensorflow as tf

model_a = snt.nets.MLP([1, 2, 3], activation=tf.nn.sigmoid)
model_b = snt.nets.MLP([1, 2, 3], activation=tf.nn.sigmoid)

# Connect modules to the graph to ensure variables are created.
x = tf.placeholder(tf.float32, [None, 1])
out_a = model_a(x)
out_b = model_b(x)

# Copy parameter values from b to a.
copy_weights = tf.group(*[va.assign(vb) for va, vb in zip(model_a.variables, model_b.variables)])

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(copy_weights)
print(sess.run({'a': out_a, 'b': out_b}, feed_dict={x: [[1.]]}))
```

**Comment by mingyr** [comment]
Dear @tomhennigan , no worries.

Thanks a lot for your alternative but more concise solution.

I will close the thread.
