### ISSUE TITLE
snt.nets.MLP: use_dropout(Type error)

### ISSUE THREAD

**Issue by KatharinaLin** [deepmind/sonnet#116]
dm-sonnet 1.23
I use "pip install dm-sonnet" to install the sonnet, get a version of 1.23.
Then I copy the code of  sonnet/sonnet/python/modules/nets/mlp_test.py line 376 in `function def testDropout(self)` , 
`
mlp_name = "test_dropout_on_mlp"
mlp = snt.nets.MLP([1], use_dropout=True, use_bias=False,activate_final=True, name=mlp_name)
`
Then I got the "TypeError":

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'use_dropout'

I have no idea what is going on,  so can you give me a hand?  Thank you~

**Comment by tomhennigan** [comment]
Hi @KatharinaLin, `use_dropout` was added to nets.MLP in Sonnet 1.26. To make sure you're on the latest Sonnet please use `pip install --upgrade dm-sonnet`.
