### ISSUE TITLE
tensorflow 2.0 support, python 3.7

### ISSUE THREAD

**Issue by flowpoint** [deepmind/sonnet#123]
hello,
is python 3.7 supported?
are there plans for supporting tensorflow 2.0 ?
if so, (how) could we contribute?
tensorflow probability is ready for 2.0 [stated here](https://github.com/tensorflow/probability/issues/320)
same issue for graph_net library ontop of sonnet [here](https://github.com/deepmind/graph_nets/issues/53)

**Comment by tomhennigan** [comment]
Hey flowpoint@, we're planning to make a major release of Sonnet to support TensorFlow 2 (c.f. deepmind/sonnet#117). The current plan is to make this public by the end of the month. We spoke a bit about this at the TF Dev Summit (https://www.youtube.com/watch?v=rlpQjnUvoKw).

Python 3.7 support I believe was blocked on TensorFlow supporting 3.7 which came out in TF 1.13 (https://github.com/tensorflow/tensorflow/releases/tag/v1.13.1), afaik there are no blockers from Sonnet, please let us know if that is not the case.

**Comment by flowpoint** [comment]
sry i managed to miss that
