### ISSUE TITLE
Config issue on macOS

### ISSUE THREAD

**Issue by davidcittadini** [deepmind/sonnet#13]
Simply follow the instructions produces the following error at the "./configure" on macOS:

Please specify the location of python. [Default is /usr/local/bin/python]:
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
sed: can't read : No such file or directory

**Comment by normanheckscher** [comment]
Works for me with OSX 10.12.4

On a side note: Mac GPU support in TensorFlow is deprecated as of the TensorFlow r1.1

**Comment by davidcittadini** [comment]
The problem is that the is_macos check fails in the sed_hyphen_i() function if you are using something like homebrew instead of the default sed.  If you are using homebrew or another version of sed on macOS then comment out everything and just leave sed -i "$@"
