### ISSUE TITLE
How to convert to bits / dim for VQ-VAE CIFAR-10 experiments ?

### ISSUE THREAD

**Issue by pclucas14** [deepmind/sonnet#131]
Hi, 

I was wondering how I can obtain the bits / dim in the VQ-VAE notebook. I tried the following: 
use MSE loss to calculate the likelihood under a standard gaussian, then add the KL term to obtain the ELBO. Finally divide by the number of pixels in an image and convert to log_e to log_2. 

However, the values I'm getting are far from the ones in the paper. Would it be possible to share code that calculates bits / dim ? Or to help me understand what I'm doing wrong ? 

Thanks in advance, 
Lucas

**Comment by pclucas14** [comment]
Also, is MSE loss actually used for CIFAR-10 ? (instead of e.g. LL under a logistic, or a 256-way softmax)

**Comment by pclucas14** [comment]
Authors answered question via email : (use a 256-way softmax, and multiple codebooks per latents)

**Comment by ryokamoi** [comment]
Hi,

>  (use a 256-way softmax, and multiple codebooks per latents)
Could you explain more about this?

How should we apply the 256-way softmax to this model?
The decoder in "vqvae_example.ipynb" returns one value for each pixel instead of 256 values.

and how can we get  multiple codebooks per latents?

**Comment by pclucas14** [comment]
I implemented the multiple codebooks [here](https://github.com/pclucas14/vq-vae/blob/master/vqvae.py#L202). As for the 256 way softmax, you can simply output 3* 236 channels instead of 3 in your last conv layer, reshape appropriately and use softmax loss. 

For what it's worth, I found that using a [discretized logistic loss](https://github.com/pclucas14/vq-vae/blob/master/utils.py#L74)  works as well and is more parameter efficient.

**Comment by ryokamoi** [comment]
Thank you so much for letting me know about your great work!
I have some last questions.

> I implemented the multiple codebooks here.

The multiple codebooks seems reasonable and effective, but was it mentioned in the papers?

> As for the 256 way softmax, you can simply output 3* 256 channels instead of 3 in your last conv layer, reshape appropriately and use softmax loss.

I see, so the authors did not use MSE for the model reported in their paper?

**Comment by pclucas14** [comment]
No, it was not mentioned in the papers (both the multiple codebooks and the 256-way softmax). I agree with you that it is quite odd indeed

**Comment by ryokamoi** [comment]
I see. Thank you very much, Lucas!
