### ISSUE TITLE
Keras Compatibility

### ISSUE THREAD

**Issue by ricvo** [deepmind/sonnet#136]
I was trying to use Keras in combination with Sonnet, in particular to wrap some keras network in a sonnet module.

```
tf.__version__
'1.14.1-dev20190527'
snt.__version__
'1.32'
```

I tried in the two following ways:
```
import tensorflow as tf
import sonnet as snt

class KerasWrapper_v1(snt.AbstractModule):
    def __init__(self, name="keras_v1"):
        super().__init__(name=name)
        
        with self._enter_variable_scope():
            self._layer = tf.keras.layers.Conv2D(32, 2, padding='SAME')
    
    def _build(self, inputs):
        return self._layer(inputs)


class KerasWrapper_v2(snt.AbstractModule):
    def __init__(self, name="keras_v2"):
        super().__init__(name=name)
    
    def _build(self, inputs):
        self._layer = tf.keras.layers.Conv2D(32, 2, padding='SAME')
        return self._layer(inputs)

x = tf.placeholder(tf.float32, shape=[None, 28, 28, 1])

mod1 = KerasWrapper_v1()
out1 = mod1(x)
out2 = mod1(x)
#this seems fine

mod2 = KerasWrapper_v2()
out1 = mod2(x)
out2 = mod2(x)

ValueError: Trainable variable created when calling a template after the first time, perhaps you used
tf.Variable when you meant tf.get_variable: [<tf.Variable 'keras_v2_1/conv2d_2/kernel:0'
shape=(2, 2, 1, 32) dtype=float32>, <tf.Variable 'keras_v2_1/conv2d_2/bias:0'
shape=(32,) dtype=float32>]

```

The `with self._enter_variable_scope():` in the init seems fundamental, building keras layers in the `_build` does not seem compatible with the scopes, maybe because keras is using tf.Variable under the hood (?)
I would be glad if you could help me to understand better the origin of this problem and if the first class KerasWrapper_v1 is supposed to behave as one would expect?
I am wondering if there is compatibility between sonnet and keras layers and if there are some other issues related to this?

**Comment by malcolmreynolds** [comment]
Hi @ricvo,

This is pretty much what I would expect to happen. Sonnet wraps tf.make_template, and anything called inside the template which creates variables has to do so with `tf.get_variable`. If the thing you're wrapping doesn't do that, as appears to be the case here, then the template breaks. This is not something that's really feasible or desirable to fix at this stage for TF 1.

As you figured out, initialising some Keras layer inside the constructor in a `self._enter_variable_scope()` will stop this problem at least, but there could be other subtle behaviours - for example, I'm not sure if custom getters as they are used in Sonnet will work inside the Keras part of your model. I would consider any mixing of Sonnet & Keras in TF v1 to be unsupported, anything might go wrong.

The good news is that in TF 2, Keras and Sonnet share a base class, so certainly basic functionality (eg, querying a top level module for all the variables it contains) will correctly work with arbitrary nestings of the two libraries. I still wouldn't necessarily _recommend_ it, you're always going to have a better experience sticking to one library or the other, but it will work a lot better than it does now. If you're interested, Sonnet for TF2 is in alpha here: https://github.com/deepmind/sonnet/tree/v2

Closing, but please reopen if you have further questions.
