### ISSUE TITLE
Following your install guide can't succeed install sonnet

### ISSUE THREAD

**Issue by kaifuluca2016** [deepmind/sonnet#146]
Your installation only one way. that's impossible suitable for every situation. 
Absolutely someone not using GPU, right? Did you do lots of test for your installation yet? 
Did you one installation suitable any situation windows, ubuntu, mac os, centos, redhat, ... at lease you need to provide with GPU , non-GPU two basic installations, right?

**Comment by tomhennigan** [comment]
Hi @kaifuluca2016, Sonnet 2 (unlike Sonnet 1) is a pure Python library so there is only one version of the library to install for all situations (regardless of operating system or GPU/non-GPU).

TensorFlow itself has also [recently changed](https://groups.google.com/a/tensorflow.org/d/msg/discuss/O_YIjW5vWp0/41u69M1oDgAJ) such that the GPU version will work even if you don't have a GPU.

As such the instructions in the README are actually accurate for any OS or GPU/non-GPU 😄, they just assume that you can install packages via `pip`. If you are unsure about how to use `pip` on your system please consult [this TensorFlow documentation](https://www.tensorflow.org/install/pip). Once you have installed TensorFlow you should find installing Sonnet very simple.

**Comment by kaifuluca2016** [comment]
Hi Tom,
Get it. Thank you so much! Have a nice weekend.
Alan Kaifu Lu
