### ISSUE TITLE
About the LSTM module usage

### ISSUE THREAD

**Issue by Jarvis-K** [deepmind/sonnet#148]
I wonder the `snt.lstm`  can be combined into `snt.sequential`. For example:
```python
snt.Sequential([
snt.LSTM(xxx),
snt.MLP(xxx)
])
```
If this can be achieved, can you show me an example?

**Comment by malcolmreynolds** [comment]
I'm assuming that you want to create a recurrent module, which can be used in `tf.nn.dynamic_rnn`(for TF v1) etc, and which consists of an LSTM and MLP in sequence? This can be done but not with Sequential, that is strictly for chains of feed forward modules. Try:

```python
my_module = snt.DeepRNN([snt.LSTM(...), snt.MLP(...)])
```

`DeepRNN` looks at all the modules provided, works out which ones are recurrent (eg you could have two LSTMs with an MLP between them, meaning that the recurrent state size of the overall module is `((first_lstm_h, first_lstm_c), (second_lstm_h, second_lstm_c))`.

You can see examples of this for TF v1 here: https://github.com/deepmind/sonnet/blob/master/sonnet/examples/rnn_shakespeare.py - obviously lots needs to change for TF/Sonnet v2, but the core way in which you compose modules together is the same.

**Comment by Thompson-Liu** [comment]
I'm working on the example you suggested with TF/Sonnet v2. It seems like in v1, the deepRNN defined using sonnet can be substituted directly into tensorflow dynamic_rnn as the cell. Starting from v2, the cell for tensorflow RNN requires to implement the call method and other things. I wonder if there's an example showing how to accomplish this for TF/sonnet. v2. Thanks
