### ISSUE TITLE
Excuse me, what time can support Python3. X?Have this plan?

### ISSUE THREAD

**Issue by Yangxulei** [deepmind/sonnet#15]
Excuse me, what time can support Python3. X?Have this plan?

**Comment by bfredl** [comment]
It seems to be mostly supported already, but some fixes are needed. See #10. At least all functionality used by `rnn_shakesphere.py` works fine.

**Comment by diegolascasas** [comment]
Commit https://github.com/deepmind/sonnet/commit/578e3360741891428ea51c36741bbabc82265942 should add python3 support. I'm closing this issue, but please create a new one or reopen it if you have any problems with python3 compatibility.
