### ISSUE TITLE
Difference between sonnet and tensorflow

### ISSUE THREAD

**Issue by huiwenzhang** [deepmind/sonnet#152]
Hi, I am using sonnet version 1.32. I found that it is so confusion between sonnet and tensorflow. In sonnet, we don't have placeholders. From this perspective,  it seems work like Pytorch. But when I want to check  the output of the networks, it is still a tensor. What's happening there?

**Comment by tomhennigan** [comment]
Hey @huiwenzhang, I would suggest upgrading to Sonnet 2.0 (and TensorFlow 2.0) to get an experience more like PyTorch:

```
$ pip install tensorflow-gpu tensorflow-probability
$ pip install "dm-sonnet>=2.0.0b0" --pre
```

Please take a look at one of our examples to see how to use Sonnet with TensorFlow 2.0: https://colab.research.google.com/github/deepmind/sonnet/blob/v2/examples/mlp_on_mnist.ipynb

In general TensorFlow and Sonnet pass `tf.Tensor` instances around. You can convert the result of the function into a numpy array using `x.numpy()`. For example the following program will print logit values from `net`:

```python
import tensorflow as tf
import sonnet as snt

net = snt.nets.MLP([1000, 100, 10])
logits = net(tf.ones([8, 28 * 28]))
print(logits.numpy())
```
