### ISSUE TITLE
Request for Conv1D to support [WNC] input format

### ISSUE THREAD

**Issue by episodeyang** [deepmind/sonnet#153]
in pyTorch the convention places the time dimension first. This is convenient for RL and is extensively used in code bases.

Currently the Conv1D in sonnet (v1) only supports (batch, sequence_length, element_size) in the "NWC" format. Can we add support to 'WNC' format to the Conv1D?

https://pytorch.org/docs/stable/nn.html#gru

*Update*: it seems the Conv1D in Pytorch also uses [NWC] convention, for it is awkward otherwise for conv modules.

https://pytorch.org/docs/stable/nn.html#conv1d

**Comment by tamaranorman** [comment]
Unfortunately the same is true of the kernals that Sonnet uses that it would be awkward to support WNC as it is in PyTorch. Supporting it would involve transposing the input before running it through the kernal and transposing it again afterwards. I don't think we want to do this by default as it can be costly so it may be worth thinking about how often/where you want to perform the transpose.

If you want something like this in your code you could wrap snt.Conv1D like this:
```
class WNCConv1D(snt.Module):
  def __init__(self, *args, **kwargs):
    self._conv = snt.Conv1D(*args, **kwargs)

  def __call__(self, inputs):
    inputs = tf.transpose(inputs, [1, 0, 2])
    outputs = self._conv(inputs)
    return tf.transpose(outputs, [1, 0, 2])
```
