### ISSUE TITLE
He initialization

### ISSUE THREAD

**Issue by joaogui1** [deepmind/sonnet#160]
The default initialization for [linear](https://github.com/deepmind/sonnet/blob/v2/sonnet/src/linear.py#L77) and convolutional modules seems to be Glorot initialization, but for the commonly used ReLU activation function [He initialization](https://arxiv.org/abs/1502.01852) is superior, while only requiring a quick change to the stddev definition, should we implement better defaults?
I know that there are many initialization schemes, I only suggest it as it would't be computationally expensive and would also be only a minor code change.

**Comment by tomhennigan** [comment]
Hey @joaogui1 as with deepmind/dm-haiku#6 this is available via the variance scaling initializer. We've included the various ways of driving this in the docs https://sonnet.readthedocs.io/en/latest/api.html#variancescaling.
