### ISSUE TITLE
version conflict in example

### ISSUE THREAD

**Issue by peterwilson3912** [deepmind/sonnet#166]
![image](https://user-images.githubusercontent.com/36145675/76986590-3ce51880-6918-11ea-993d-3a64835fe783.png)

**Comment by tomhennigan** [comment]
Thank you for the report @karliell , we have pushed a `2.0.0` release of Sonnet now so you can just do `!pip install dm-sonnet`.

There is also a new `1.1.0` release of `graph-nets` which has been picked up by colab which is compatible with TF2 and Sonnet 2 ([example here](https://github.com/deepmind/graph_nets/blob/f7db5fd9d531544d5b2fb285b1a6ed3352dd0192/graph_nets/demos_tf2/models.py)).

I think thigs are working correctly now, please re-open if not!
