### ISSUE TITLE
Colab mnist example does not work

### ISSUE THREAD

**Issue by VogtAI** [deepmind/sonnet#169]
https://colab.research.google.com/github/deepmind/sonnet/blob/v2/examples/mlp_on_mnist.ipynb

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in to_graph(entity, recursive, experimental_optional_features)
    661         autograph_module=tf_inspect.getmodule(to_graph))
--> 662     return conversion.convert(entity, program_ctx)
    663   except (ValueError, AttributeError, KeyError, NameError, AssertionError) as e:

26 frames
AssertionError: Bad argument number for Name: 4, expecting 3

During handling of the above exception, another exception occurred:

ConversionError                           Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in to_graph(entity, recursive, experimental_optional_features)
    664     logging.error(1, 'Error converting %s', entity, exc_info=True)
    665     raise ConversionError('converting {}: {}: {}'.format(
--> 666         entity, e.__class__.__name__, str(e)))
    667 
    668 

ConversionError: converting <function BaseBatchNorm.__call__ at 0x7f09acc45ae8>: AssertionError: Bad argument number for Name: 4, expecting 3

**Comment by VogtAI** [comment]
It does work when changing to gast version 0.3.3
!pip install dm-sonnet==2.0.0b0 gast==0.3.3 tqdm

**Comment by tomhennigan** [comment]
Thanks for the report! We will update these lines to be `!pip install dm-sonnet tqdm` since the latest version of TF does not pin a broken version of gast 😄
