### ISSUE TITLE
Variables that aren't shared?

### ISSUE THREAD

**Issue by jyegerlehner** [deepmind/sonnet#17]
In the MyMLP example, it says:

> new instances of snt.Linear are generated each time _build() is called, and you may think this will create different, unshared variables. This is not the case - only 4 variables (2 for each Linear) will be created, no matter how many times the MLP instance is connected into the graph. ****

So... what if I don't want the variables to be shared? For example, suppose I wanted to have a deeper net by stacking 4 MyMLP instances. I want each of them to have their own weights, not to share weights. Is this just not possible?

**Comment by crossonrose** [comment]
It better be or the sum may be incorrect.

**Comment by jyegerlehner** [comment]
Ah, perhaps I didn't construe the statement in the docs correctly. It doesn't say the variables are shared across multiple instances of MyMLP. It says given a single instance of MyMLP that is connected into the graph multiple times that the variables are shared. 

I should just try it out. Closing in the mean time.
