### ISSUE TITLE
Normalization of weights during EMA update of VQ-VAE

### ISSUE THREAD

**Issue by stangelid** [deepmind/sonnet#170]
Hello,

The snippet below is the EMA update for VQ-VAE:

https://github.com/deepmind/sonnet/blob/cd5b5fa48e15e4d020f744968f5209949ebe750f/sonnet/python/modules/nets/vqvae.py#L224-L238

I noticed that the order of computations is not what I was expecting from reading the paper equations. In particular, in line 228, you perform an EMA update which combines the **normalized** code-book weights `self._ema_w` with the **yet unnormalized** weights `dw`. The updated weights are then normalized in line 235, by dividing with the updated cluster sizes.

The order that seems more natural to me is:

1. Update (EMA) `self._ema_cluster_size` using new assignment counts.
2. Compute `dw`.
3. Normalize `dw`, i.e., divide by `self._ema_cluster_size`.
4. Update (EMA) `self._ema_w` using normalized `dw`.

The difference is small, but I believe my suggestion is faithful to what is described in the paper. Is there a reason why you've implemented it this way? Did you notice better training stability this way?

Thanks,
Stefanos

**Comment by stangelid** [comment]
Bumping to see if there is an explanation for the above?

**Comment by malcolmreynolds** [comment]
Hi @stangelid apologies for the delay. I checked with Aäron van den Oord and he sent the following:

```
Hi Stefanos,
self._ema_w are the moving averages of the unnormalized weights.
https://arxiv.org/pdf/1711.00937.pdf
Equation (9) in the Appendix defines the weights (e_i) as
- The moving averages of the unnormalized weights (sum of z_ij)
- Divided by the moving averages of the counts of the codebook (sum of number of elements in each cluster)
This seems to correspond well with the code?
```
`

**Comment by stangelid** [comment]
Thanks for the clarification. I now realise that `self._ema_w` remains unnormalized throughout training, so my concern doesn't apply.
