### ISSUE TITLE
Train on own dataset 

### ISSUE THREAD

**Issue by nadiagit** [deepmind/sonnet#171]
Hi, did someone tried to train VQ-VAE on her/his own data set of images? I would like some help :)
Thank you.

**Comment by malcolmreynolds** [comment]
Hi - I'm afraid this isn't the best place for open ended questions like this - I would advise to try a larger online community (reddit, stackexchange, ...) for this kind of discussion. If you have a specific question about the code please post here, and a specific question about the model would be best forwarded to the original authors: https://arxiv.org/abs/1711.00937
