### ISSUE TITLE
Sonnet 2.0.0 has no 'RelationalMemory'?

### ISSUE THREAD

**Issue by yuriufo** [deepmind/sonnet#175]
```Python
import sonnet as snt
...
snt.RelationalMemory(...)
...
```
Then it raises a Exception:
`module 'sonnet' has no attribute 'RelationalMemory'`

**Comment by Jack-Halloran-1** [comment]
Did you manage to resolve this issue? I can't find relational memory in this GitHub, but it was recommended by ChatGPT when I asked it for advice on composing a Differential Neural Computer.
