### ISSUE TITLE
LSTM, RNN and GRU "prev_state" parameter unclear

### ISSUE THREAD

**Issue by AverageHomosapien** [deepmind/sonnet#177]
Hello, I'm attempting a Sonnet implementation of a model with an LSTM and have run into trouble.

In the documentation, there is no type listed for the RNN base class parameter "prev_state" and no additional documentation. The LSTM, GRU and VanillaRNN implementations don't have any information, and just reference the RNN base class.

"prev_state" requires .cell and .hidden attributes, however I don't see Sonnet classes with either of those attributes implemented. I've listed example calls below from the recurrent.py package:

```python
gates_h = tf.matmul(prev_state.hidden, w_h) # Line 896
```
```python
next_cell = tf.sigmoid(f) * prev_state.cell # Line 902
```

Can you please advise?
Thank you!

**Comment by malcolmreynolds** [comment]
@hamcam98 the `prev_state` supplied on input will be the same shape as whatever that module returns from the `initial_state` method (this is true for all the different RNN modules). So for the LSTM you can see there is a LSTMState namedtuple, that has the `.hidden` and `.cell` attributes: https://github.com/deepmind/sonnet/blob/v2/sonnet/src/recurrent.py#L848

I hope this answers your question, please reopen if not.

**Comment by AverageHomosapien** [comment]
Thank you for quick response! Has solved my issue.
