### ISSUE TITLE
Device Placement with Tensorflow 2

### ISSUE THREAD

**Issue by agnusmaximus** [deepmind/sonnet#179]
I'm trying to specify execution of a Sonnet module on the CPU instead of the GPU. How can I specify device placement of Sonnet modules in Tensorflow 2? A previous issue suggested using functions with tf.device like this:
```
from tensorflow.core.framework import node_def_pb2

[...]
def device_setter(op):
  _variable_ops = ["Variable", "VariableV2", "VarHandleOp"]
  node_def = op if isinstance(op, node_def_pb2.NodeDef) else op.node_def
  return  '/cpu:0' if node_def.op in _variable_ops else '/gpu:0'
[...]   

with tf.device(device_setter):
  outputs = rcnn_output(t)
```

However, with tensorflow 2, tf.device can no longer accept functions as arguments. How can I work around this?

**Comment by tomhennigan** [comment]
Hi @agnusmaximus if you want to run on the CPU then create and use your modules inside a `with tf.device("CPU"):` block. For example:

```python
x = tf.ones([1, 28 * 28])
with tf.device("CPU"):
  mod = snt.nets.MLP([300, 100, 10])
  logits = mod(x)
```

It may be useful to know that outside of a `with tf.device` scope TensorFlow's default device placement policy will silently move tensors from the CPU to the GPU, you may want to set TF's device policy to explicit if you want to ensure all computation remains on the CPU:

```python
tf.config.experimental.set_device_policy("explicit")
```

If you want your whole TF program to only run using CPU then you can configure TensorFlow to ignore all other devices using the following at the start of your program:

```python
# Ignore all devices other than available CPU(s).
cpus = tf.config.list_physical_devices("CPU")
tf.config.set_visible_devices(cpus)
```

**Comment by agnusmaximus** [comment]
Awesome, thank you!
