### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by leconteur** [deepmind/sonnet#18]
Is windows support planned? 

I didn't manage to run the ./configure script of tensorflow. However, by moving the BUILD file to a new name, i could install sonnet by doing a simple 
`python setup.py install`

I did not encounter bugs other than the complicated setup.

**Comment by cumttang** [comment]
It;s not work at last. Although there is not bug while installing, it raised the Import Error while using the verify example.

**Comment by leconteur** [comment]
Check that you did not try the example from the sonnet folder, it often doesn't work.

**Comment by cumttang** [comment]
![image](https://cloud.githubusercontent.com/assets/16380725/25299856/3688b4b4-2736-11e7-94ac-18254dcecc29.png)

Not that. It just the example to use the resampler from sonnet.

**Comment by kosklain** [comment]
Hey, after a bit of discussion, Windows support is not on the roadmap at the moment. Of course, PRs are always welcome :)

Just adding a note to this: @leconteur  your installation (without compilation) will not include the C++ bits of our library (currently that is the resampler).
