### ISSUE TITLE
How to install to Jetson

### ISSUE THREAD

**Issue by n-kats** [deepmind/sonnet#186]
The cpu architecture of Nvidia Jetson is aarch64. So, I failed to install sonnet to Jetson.
I read the following message:
```
unable to execute 'bazel': No such file or directory
error: command 'bazel' failed with exit status 1 
```

I installed bazel. I downloaded it from the release page of bazel, moved it to /bin/bazel, and made it executable by chmod.
(I used https://github.com/bazelbuild/bazel/releases/download/3.4.1/bazel-3.4.1-linux-arm64)
After then, I succeeded to install sonnet.
Is this way correct?

I think someone also will try install sonnet to Jetson. So, the following may be useful:
* write how to install to Jetson(using bazel)
* add wheels for aarch64(dm-tree for aarch64 is missing in [pypi](https://pypi.org/project/dm-tree/#files)).

Thank you.

**Comment by superbobry** [comment]
Thanks for writing this up!

Neither Sonnet 1 nor `tree` have wheels for aarm64, and I'm afraid this will remain the case for a while. So, the only way of installing Sonnet 1 on Jetson is indeed by downloading Bazel (as you did) and building both `tree` and Sonnet 1 from source. Note that you'll likely have to build TensorFlow from source as well for the same reason.

**Comment by n-kats** [comment]
Sorry, I talked about Sonnet2. But, it will be a little thing.
I see. I'll use Bazel for installation. Thank you.

As you may know, Nvidia published wheels of TensorFlow for Jetson in [https://developer.download.nvidia.com/compute/redist/jp/v44/tensorflow/](https://developer.download.nvidia.com/compute/redist/jp/v44/tensorflow/). However, thers is a delay in releasing latest versions.

**Comment by superbobry** [comment]
Interesting. I think the wheels for Sonnet 2 are platform-agnostic because Sonnet 2 does not have any native code. So you only really need to build `tree`.

**Comment by n-kats** [comment]
I found tensorflow-probability also depends on dm-tree and needs bazel.
