### ISSUE TITLE
self.enter_variable_scope()

### ISSUE THREAD

**Issue by Pranav-India** [deepmind/sonnet#196]
I am not to understand the working of this and where is this defined. Can anyone please help with this? also if there is some slack channel or forum where I can ask my questions that will of great help. Thank you

**Comment by tomhennigan** [comment]
Hi @Pranav-India, that API is only used in Sonnet 1 which only supports TensorFlow 1 and is deprecated.

If you need to use TensorFlow 1 for some reason then you can find the source for Sonnet 1 in the `master` branch, the method is defined here https://github.com/deepmind/sonnet/blob/master/sonnet/python/modules/base.py#L536.

We recommend that new projects use Sonnet 2 and TensorFlow 2. You can find documentation on Sonnet 2 at https://sonnet.readthedocs.io/en/latest/.

We use GitHub issues for discussion and don't have a Slack/Discord I'm afraid.
