### ISSUE TITLE
Issue while import sonnet

### ISSUE THREAD

**Issue by pshrini** [deepmind/sonnet#197]
ConversionError: converting <function BaseBatchNorm.call at 0x00000268C3EF7950>: AttributeError: module 'gast' has no attribute 'Constant'
My gast version is 0.3.3
Tensorflow 2.3.1
graph-nets 1.1
How I installed graph-nets
pip install "graph_nets>=1.1" "tensorflow>=2.1.0-rc1" "dm-sonnet>=2.0.0b0" tensorflow_probability

**Comment by tomhennigan** [comment]
Hi @pshrini I think this is a TF issue not a Sonnet issue (we do not depend on or use `gast` directly but TF does).

I would suggest making sure you have the latest version of TensorFlow ([2.4.1](https://pypi.org/project/tensorflow/2.4.1/) has been released recently) and all other deps. If you continue to have issues after upgrading I would suggest filing an issue on TensorFlow.
