### ISSUE TITLE
Where can I acquire sonnet 1.x documentation?

### ISSUE THREAD

**Issue by wxhaooo** [deepmind/sonnet#200]
Hi! I work on some library which build on sonnet 1.x. But I can not find 1.x documentation on your website. would you consider re-release 1.x documentation?

**Comment by tomhennigan** [comment]
Hi @wxntech , we don't have a hosted copy (e.g. on github pages) of Sonnet 1 docs any longer, but you can still find the code for 1.x in the [`master`](https://github.com/deepmind/sonnet/tree/master) branch, and the [docs for the last commit can be found here](https://github.com/deepmind/sonnet/blob/master/docs/index.md) and [per-public symbol docs can be found here](https://github.com/deepmind/sonnet/blob/master/docs/sonnet.md).
