### ISSUE TITLE
Sonnet assertion error: Sonnet v2 requires Tensorflow 2

### ISSUE THREAD

**Issue by efriesema** [deepmind/sonnet#204]
I'm running Ubuntu 20.04 LTS  and Python 3.7
Tensorflow 2.5.0
Sonnet 2.0.0.
running the following code
after having just pip installed tensorflow and dm-sonnet

import tensorflow as tf
import sonnet as snt

print("TensorFlow version {}".format(tf.__version__))
print("Sonnet version {}".format(snt.__version__))

batch_size = 32
input_size = (28,0)
mlp = snt.Sequential([
    snt.Linear(1024),
    tf.nn.relu,
    snt.Linear(10),
])

I received the following error
 File "/home/efriesema/anaconda3/envs/DHPKG/lib/python3.7/site-packages/sonnet/src/base.py", line 372, in assert_tf2
    assert tf.executing_eagerly(), "Sonnet v2 requires TensorFlow 2"

AssertionError: Sonnet v2 requires TensorFlow 2

I've confirmed that i am running tensorflow 2.5   tf.executing eagerly() returns false but that could happen for other reasons besides the one they present ie that I'm  not running Tensorflow 2.0

**Comment by tomhennigan** [comment]
HI @efriesema , we test wtith TensorFlow 2.5 (e.g. https://github.com/deepmind/sonnet/runs/2792353483?check_suite_focus=true) so I don't think that will be the issue.

If you run just the following, does it print the version you expect:

```python
import tensorflow as tf
print("TensorFlow version {}".format(tf.__version__))
```

You may want additionally to try installing the latest version from the github repo rather than the last stable release:

```python
pip install pip install git+https://github.com/deepmind/sonnet@v2
```

**Comment by efriesema** [comment]
Thanks Tom,  the pip install from github seems to have fixed the problem


Ed Friesema
Check out my github page www.github.com/efriesema for my latest projects!

**Comment by efriesema** [comment]
BTW Tom  I'm working on Argonne Labs on a summer internship and have been
tasked with building a reinforcement learning system with the vtrace
algorithm using Open gym as the environment.  We are trying to solve a
special reinforcement learning problem and we want to uses a scalable
architecture so we can parallelize the problem I'm trying to repurpose your
experiment.py and vtrace.py from your scalable-agent repo.  and replace the
environment with open gym instead of deep mind lab.  Is there anyone on
your team who might be able to give me some pointers.  I'm drinking from
the firehose here.

Ed Friesema
Check out my github page www.github.com/efriesema for my latest projects!

**Comment by tomhennigan** [comment]
I'd suggest taking a look at [deepmind/acme](https://github.com/deepmind/acme) which has a number of RL agents (e.g. [IMPALA](https://github.com/deepmind/acme/tree/master/acme/agents#discrete-control)) implemented with Sonnet 2 which [use vtrace in the learner](https://github.com/deepmind/acme/blob/fce4a6ef901f6bc82311845f13a9a2699cbab585/acme/agents/tf/impala/learning.py#L133). They also include an [example which uses gym](https://github.com/deepmind/acme/blob/master/examples/control/run_d4pg_gym.py).
