### ISSUE TITLE
Multiple inputs to sonnet network

### ISSUE THREAD

**Issue by DriesSmit** [deepmind/sonnet#212]
Hello there. How can I use sonnet to set up a network that takes in a 1D convolutional input as well as a 1D vector input? The idea is that the first part of the input gets processed by a 1D conv net and then the output gets flattened and goes through a ff layer. This output is then concatenated to the second input. Then this flattened vector gets fed to higher up levels in the network. Is this possible?

Thanks!

**Comment by tomhennigan** [comment]
Hi @DriesSmit , Sonnet 2 does not impose any restrictions on what methods you define or what you pass into them. You can find more details on the design in this RFC: https://github.com/tensorflow/community/blob/master/rfcs/20190117-tf-module.md

I guess your module might look something like the following:

```python
class MyModule(snt.Module):
  def __init__(self):
    self.conv = snt.Conv1D(..)
    self.ff = snt.Linear(..)

  def __call__(self, a, b):
    a = self.conv(a)
    a = tf.nn.relu(a)
    a = self.flatten(a)
    a = self.ff(a)
    return tf.stack(a, b)
```
