### ISSUE TITLE
Resnet

### ISSUE THREAD

**Issue by DriesSmit** [deepmind/sonnet#213]
Hey there,

I am trying to understand where the skip connections are in your [resnet](https://github.com/deepmind/sonnet/blob/0e25f47fac469c0c2180abba0b985aca46f529ce/sonnet/src/nets/resnet.py#L182) implementation? I would love to use it but I am having trouble understanding this minor detail. Thanks!

**Comment by tomhennigan** [comment]
Hi @DriesSmit I think we call them `shortcut` in the code. You should be able to see them in the `__call__` method of the blocks:

https://github.com/deepmind/sonnet/blob/0e25f47fac469c0c2180abba0b985aca46f529ce/sonnet/src/nets/resnet.py#L91-L104
 https://github.com/deepmind/sonnet/blob/0e25f47fac469c0c2180abba0b985aca46f529ce/sonnet/src/nets/resnet.py#L166-L179

**Comment by DriesSmit** [comment]
I see thanks :+1:
