### ISSUE TITLE
Does LayerNormMLP work with batch_sizes of one?

### ISSUE THREAD

**Issue by DriesSmit** [deepmind/sonnet#220]
Good day,

I am using sonnet's LayerNormMLP layer inside a policy for reinforcement learning. Does this layer normaliser still work when a batch size of 1 is used by the actors? For the trainer a batch of data is provided so layer normalisation should work. Thanks!

**Comment by tomhennigan** [comment]
Hi @DriesSmit , I'm not familiar with `LayerNormMLP` (as in the implementation you are using, I can guess as to what the architecture is) in particular, but in general `LayerNorm` and `MLP` should work fine at batch size 1.
