### ISSUE TITLE
Is there a convenient way to print output shape of every layer?

### ISSUE THREAD

**Issue by RlChen0** [deepmind/sonnet#232]

**Comment by tomhennigan** [comment]
We don't have a built in way to do this, but you can monkey patch modules and add your own print statements. Here is an example that hooks every call method of every module class and prints input/output shapes:

https://colab.research.google.com/gist/tomhennigan/ebcee49d928c2c7f2e868d3552a8f85b/example-of-printing-call-method-input-and-output-shapes.ipynb

**Comment by RlChen0** [comment]
thanks, help a lot.
