### ISSUE TITLE
Understanding how to use mixed precision training

### ISSUE THREAD

**Issue by isabellahuang** [deepmind/sonnet#238]
I want to used mixed precision training in my models to increase performance. It would be great to use float32 variables but float16 computation, like what [mixed_precision.Policy in Keras](https://www.tensorflow.org/guide/mixed_precision) does. 

The [Sonnet documentation](https://sonnet.readthedocs.io/en/latest/api.html#module-sonnet.mixed_precision) provides the following example
```
>>> support_modes = snt.mixed_precision.modes([tf.float32, tf.float16])
>>> snt.Linear.__call__ = support_modes(snt.Linear.__call__)
>>> mod = snt.Linear(10)
>>> snt.mixed_precision.enable(tf.float16)
>>> y = mod(tf.ones([1, 1]))  # First call will be done in F32.
>>> y = mod(tf.ones([1, 1]))  # MatMul/Add will be done in F16.
>>> snt.mixed_precision.disable()
```

1. When I run this on my machine, both calls to `y = mod(tf.ones([1, 1]))` yields y as a float32 tensor. I thought `snt.mixed_precision.enable(tf.float16)` would cast y to a float16 tensor. What does the dtype in the enable() function mean then? 

2. Why does this example have two calls to `y = mod(tf.ones([1, 1]))`? It is to show that the first time, all computation will be done in float32, but all subsequent calls to mod will use float16 for computation? And yet, that the output tensor y will always have a consistent type (in this case, float32)?

3. Do I have to use `snt.mixed_precision.enable(tf.float16)` and `snt.mixed_precision.disable()` if I already wrap `snt.Linear.__call__` with the support_modes decorator? I'm pretty unclear on the differences between these. 

4. Lastly, how do I activate mixed precision training on a custom module of mine, which inherits from snt.Module?  
I'm following the example and doing the following:

```
support_modes = snt.mixed_precision.modes([tf.float32, tf.float16])
core_model.EncodeProcessDecode.__call__ == support_modes(core_model.EncodeProcessDecode.__call__)


learned_model = core_model.EncodeProcessDecode(
    output_size=output_size,
    latent_size=FLAGS.latent_size,
    num_layers=FLAGS.num_layers,
    message_passing_steps=FLAGS.message_passing_steps)
```

But the TF profiler is still saying that 0.0% of my computation is using 16-bit ops, so I don't think I'm doing this right.

**Comment by tomhennigan** [comment]
Hi @isabellahuang , from your example it looks like you might be missing a call to `snt.mixed_precision.enable(tf.float16)`.

Here is an example of using mixed f32/f16: https://colab.research.google.com/gist/tomhennigan/2d54c6660b50f66a79699f419c8d7307/example-of-mixed-precision-in-sonnet-2.ipynb which includes a routine to check the tf graph for operations in f16/f32.

If you are looking to speed up training in general, then a quick win would be to pass `jit_compile=True` to `@tf.function` which will compile your program using XLA.

**Comment by isabellahuang** [comment]
Thank you @tomhennigan , that colab was very informative. Would be a great addition to the docs.
