### ISSUE TITLE
cannot make sonnet working!!

### ISSUE THREAD

**Issue by arnaghizadeh** [deepmind/sonnet#24]
Hi, I'm trying to simply install sonnet, but it is not working. I used instructions on the first page and also did sudo python setup.py build && python setup.py install 

it seems to be installed fine but I get the following error, can someone tell me what is going on?:
`
>>> import sonnet as snt
>>> import tensorflow as tf
>>> snt.resampler(tf.constant([0.]), tf.constant([0.]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sonnet/python/ops/resampler.py", line 65, in resampler
    raise ImportError("_gen_resampler could not be imported.")
ImportError: _gen_resampler could not be imported.

`

**Comment by arnaghizadeh** [comment]
As an update, I used [this](https://github.com/deepmind/sonnet/issues/5#issuecomment-292795066) method (takes a lot of time to compile) and it seems to be working. Currently I cannot run sonnet properly from official instructions.

**Comment by normanheckscher** [comment]
@arnaghizadeh it looks like an older version of tensorflow is needed. Working around tensorflow @ 36a47f2 is the only way I've been able to get Sonnet running.

**Comment by gyang1011** [comment]
@arnaghizadeh I follow the instruction in your link but I still encounter this problem:
      ImportError: _gen_resampler could not be imported

Is /tmp/tensorflow_pkg/tensorflow-1.1.0rc1-cp27-cp27mu-linux_x86_64.whl a gpu version of tensorflow?

**Comment by arnaghizadeh** [comment]
I use virtual box so I chose to disable CUDA (no GPU and OpenCL)

**Comment by smizy** [comment]
@gyang1011  try "/tmp/tensorflow_pkg/tensorflow-1.1.0-cp27-cp27mu-linux_x86_64.whl".
"rc1" string seems to be removed in r1.1 branch.
I also follow the above instruction and have successfully installed on [alpine based docker image](https://github.com/smizy/docker-sonnet). resampler output is fine.

**Comment by gyang1011** [comment]
I got it working. Thanks guys!

**Comment by kosklain** [comment]
Closing and following progress on #25 (apart from having the workaround that you point out).

**Comment by danisbohan** [comment]
I've met same trouble. What about a windows user? How to make it work on Windows 10 with Tensorflow and Sonnet
