### ISSUE TITLE
_resampler.so: undefined symbol

### ISSUE THREAD

**Issue by animesh** [deepmind/sonnet#25]
faced this error while executing the example code
````
import sonnet as snt
import tensorflow as tf
snt.resampler(tf.constant([0.]), tf.constant([0.]))
````
recompiling the tensorflow to 1.1.0-rc2 and replacing the downloaded sonnet/tensorflow with this one solved the problem :)

**Comment by thesilencelies** [comment]
I checked out the 1.1 branch of tensorflow in the one in the sonnet tree, compiled tensorflow from that (which works), then rebuilt sonnet. However I still get the above error for _ZN10tensorflow8internal21checkOpMessageBuilder9NewString. I had the warning mentioned in #16 during build.
I guess I did something wrong, but I'm a little unsure how to implement the solution mentioned above...

**Comment by bgavran** [comment]
I have the same problem as @thesilencelies. I did a git pull in sonnet/tensorflow after which I followed the sonnet installation instructions, but I still get the _resampler.so: undefined symbol error

**Comment by PFCM** [comment]
I'm also getting this as per @thesilencelies. Tried tensorflow 1.1.0, then 1.1.0-rc2 when that didn't work. In both cases `ldd` on the produced `_resampler.so` shows:
```
        linux-vdso.so.1 =>  (0x00007ffe9c52b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f87868d3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f87866b5000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f878632d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8786116000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8785d4f000)
        /lib64/ld-linux-x86-64.so.2 (0x000055b1b0e70000)
```

ie. it doesn't look as if the op library is being linked to anything tensorflow related? Using bazel 0.4.5 on ubuntu 17.10 if it helps.

**Comment by animesh** [comment]
I again faced this issue on another machine. I downgraded to Python2.7 and
made a re-installation attempt which seems to have worked. So I would
suggest to check the Python version, seems like Python3 compatibility is
less polished...

Regards,

Ani


--------------------------"The Answer Lies In The
Genome"--------------------------

**Comment by Jazyy** [comment]
@animesh  I faced the same error and followd your ways , but I still get the _resampler.so: undefined symbol error .I guess that there might some steps were wrong in this process.

**Comment by animesh** [comment]
yeah i can imagine, there are many gotchas in setting this beast... for starter, what is your environment like? things like operating system, java, python, tensorflow and bazel versions? are you able to run everything else except sonnet?

**Comment by llbuaa2015** [comment]
use tensorflow 1.1.0-rc2 replacing the sonnet/tensorflow if 1.1.0-rc2 is used and
`bazel build --config=opt --genrule_strategy=standalone --spawn_strategy=standalone :install `
 this works for me !

**Comment by thesilencelies** [comment]
PFCM's solution worked for me.

**Comment by lengoanhcat** [comment]
@llbuaa2015's solution is working for me with Anaconda Python 3.6, Tensorflow 1.1.0-rc2 on Ubuntu 16.04 (gcc-5.4).

**Comment by urosjarc** [comment]
@PFCM I f****** love you!

**Comment by stein2013** [comment]
@PFCM Cool! I have installed sonnet almost 10 times, all failed, untill now. thank you.

**Comment by malcolmreynolds** [comment]
Anyone still having trouble - please see https://github.com/deepmind/sonnet/issues/56 - there are preliminary Wheel files available on PyPI. Please try to install and let us know how you get on.
