### ISSUE TITLE
Convert a Sonnet model to a Keras model

### ISSUE THREAD

**Issue by raphaelmourad** [deepmind/sonnet#250]
Hi,

is there a simple way to convert a model built with Sonnet into a Keras model? Like a function or something like that.

Thanks
Raf

**Comment by tomhennigan** [comment]
Hi @raphaelmourad , we don't have any public APIs in Sonnet for this, but you can see an example of how you might write a `LayerAdapter` (converts a Sonnet module with a `__call__` method to a Keras `Layer`) in our tests:

https://github.com/deepmind/sonnet/blob/7298417de2e8b6ff9f7708ecd4596293ee62577d/sonnet/src/conformance/keras_test.py#L157-L217

I think from a Keras `Layer` is is quite easy to create a Keras `Model` (if `Model` is indeed the type you want). I am not very familiar with Keras, but I think you can just do `tf.keras.Sequential(layers=[MyLayer()])`.
