### ISSUE TITLE
Regarding LearningRateSchedule for ADAM optimizer

### ISSUE THREAD

**Issue by kmukeshreddy** [deepmind/sonnet#253]
Hello,

Is there any way to use LearningRateSchedule for Sonnet Adam Optimizer?
Similar to Tf Schedule here: https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/ExponentialDecay

**Comment by kmukeshreddy** [comment]
A gentle reminder regarding the request.

**Comment by tomhennigan** [comment]
Hi, please see my answer here https://github.com/deepmind/sonnet/issues/247#issuecomment-1178988316 for an example of using exponential decay with Sonnet 2.
