### ISSUE TITLE
Configure failed on Mac OSX

### ISSUE THREAD

**Issue by CBrauer** [deepmind/sonnet#26]
I get:

>  sudo bazel build --config=opt :install
Password:
Extracting Bazel installation...
.........
WARNING: Config values are not defined in any .rc file: opt
WARNING: /private/var/tmp/_bazel_root/81097c8f44aae43fe60488543d11a0e1/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /Users/CBrauer/sonnet/sonnet/python/BUILD:119:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc:ops/resampler.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/CBrauer/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /Users/CBrauer/sonnet/sonnet/python/BUILD:119:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/CBrauer/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /Users/CBrauer/sonnet/sonnet/python/BUILD:119:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.h' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/CBrauer/sonnet/sonnet/tensorflow.bzl:108:25.
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_root/81097c8f44aae43fe60488543d11a0e1/external/gif_archive/BUILD.bazel:8:1: C++ compilation of rule '@gif_archive//:gif' failed: Process exited with status 1 [sandboxed].
couldn't understand kern.osversion `16.5.0'
cc1: error: unrecognized command line option "-Wthread-safety"
cc1: error: unrecognized command line option "-Wself-assign"
cc1: warning: unrecognized command line option "-Wno-free-nonheap-object"
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //:install failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 12.066s, Critical Path: 0.19s
>  
Please help.

Charles

**Comment by Shuolongbj** [comment]
FYI.#32

**Comment by kosklain** [comment]
@CBrauer was this a transient issue? (i.e. did the comment above solve your issue?)

**Comment by CBrauer** [comment]
Yes, I tried it again and it worked.

Thanks

Charles

**Comment by kosklain** [comment]
@CBrauer great to hear that, thanks for the response.
