### ISSUE TITLE
Basic import fails on Colab: cannot import name 'context' from 'tensorflow.python' 

### ISSUE THREAD

**Issue by drscotthawley** [deepmind/sonnet#273]
Following the minimal  testing instructions on the README...

```python
!pip install tensorflow tensorflow-probability
!pip install dm-sonnet


import tensorflow as tf
import sonnet as snt

print("TensorFlow version {}".format(tf.__version__))
print("Sonnet version {}".format(snt.__version__))
```

Results in the following error on the line that reads ` import sonnet as snt`: 

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-2-767d5afefea7>](https://localhost:8080/#) in <cell line: 2>()
      1 import tensorflow as tf
----> 2 import sonnet as snt
      3 
      4 print("TensorFlow version {}".format(tf.__version__))
      5 print("Sonnet version {}".format(snt.__version__))

1 frames
[/usr/local/lib/python3.10/dist-packages/sonnet/src/recurrent.py](https://localhost:8080/#) in <module>
     34 # pylint: disable=g-direct-tensorflow-import
     35 # Required for specializing `UnrolledLSTM` per device.
---> 36 from tensorflow.python import context as context_lib
     37 from tensorflow.python.eager import function as function_lib
     38 # pylint: enable=g-direct-tensorflow-import

ImportError: cannot import name 'context' from 'tensorflow.python' (/usr/local/lib/python3.10/dist-packages/tensorflow/python/__init__.py)
```

Here's a link to my minimal Colab example: https://colab.research.google.com/drive/1GazLC3fCqQt7x48ED0KLCt-Zqu9s4Dk_?usp=sharing

Could someone please suggest how to resolve this?

**Comment by Lilneo786** [comment]
The issue you are facing is caused by a compatibility problem between the TensorFlow and Sonnet versions you are attempting to use. The error message indicates that Sonnet is attempting to import a module called 'context' from 'tensorflow.python', but it is unable to locate it in the installed TensorFlow version.

If you want to keep using the same version of Sonnet, you can downgrade TensorFlow: 

` pip install tensorflow==2.4.0`

 Or you can update Sonnet to a version that is compatible with your current TensorFlow version:

`pip install --upgrade dm-sonnet`

**Comment by drscotthawley** [comment]
@Lilneo786 thanks for your reply.  I was just coming back after trying to update the Sonnet version, to announce that it doesn't help, when I now see your reply.  So, be aware that that 

> Or you can update Sonnet to a version that is compatible with your current TensorFlow version:
>
> pip install --upgrade dm-sonnet

Actually has no effect and produces the exact same error as before, as my Colab now shows. 

```
dm-sonnet         2.0.1
```

I will try downgrading `tensorflow` next.

**Comment by drscotthawley** [comment]
@Lilneo786  Nope, that version of tensorflow is no longer available via `pip`:
```python
ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.0 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.0.post1)
ERROR: No matching distribution found for tensorflow==2.4.0
```

Note: For each test, I performed a `Disconnect and delete runtime` to re-start from a fresh environment. 

Please let me know when the README's instructions have been updated and re-tested.

**Comment by Lilneo786** [comment]
Use a Different TensorFlow Version:  

`pip search tensorflow`


Use TensorFlow's Official Docker Images: If you specifically need TensorFlow 2.4.0, you can utilize Docker to run your code within a container that has TensorFlow 2.4.0 installed. TensorFlow provides official Docker images that include various versions of TensorFlow. Here's how you can do it:

Pull the TensorFlow 2.4.0 Docker image: 

`docker pull tensorflow/tensorflow:2.4.0`

Create and run a container using this image:

`docker run -it --rm tensorflow/tensorflow:2.4.0`

Inside this container, you should have TensorFlow 2.4.0 available.

Update Code for TensorFlow Compatibility: Alternatively, you can modify your code to work with the TensorFlow version that is readily available via pip.

**Comment by drscotthawley** [comment]
"If you specifically need TensorFlow 2.4.0,"?  You were the one who recommended that version!

Docker images in Colab??  What are you talking about? 

> Update Code for TensorFlow Compatibility: Alternatively, you can modify your code to work with the TensorFlow version that is readily available via pip.

 ??  It's not my code.

Your reply has all the non-specificity of a LLM-powered bot.  Reporting this to GitHub.

**Comment by Lilneo786** [comment]
I'm not a bot just telling you what I thought may fix the problem. sorry it didnt work, i'm still playing with your code to see if theres anything else I can do.

**Comment by Lilneo786** [comment]
I checked this on Colab, deepnote, and pycharm just to be sure but seems to be giving issues only in Colab.

Heres a link: https://embed.deepnote.com/32c0b48c-e711-49c0-90a4-f6f1a3200d56/04566bb746de42ef97d61a57198444bd/5b43e925c358484a80f92428d2c42872?height=861.7999877929688

```
!pip install tensorflow tensorflow-probability dm-sonnet
#!pip uninstall -y dm-sonnet
!pip install --upgrade dm-sonnet

import tensorflow as tf
import sonnet as snt

print("TensorFlow version {}".format(tf.__version__))
print("Sonnet version {}".format(snt.__version__))
```

Requirement already satisfied: tensorflow in /shared-libs/python3.9/py/lib/python3.9/site-packages (2.10.0)
Requirement already satisfied: tensorflow-probability in /root/venv/lib/python3.9/site-packages (0.23.0)
Requirement already satisfied: dm-sonnet in /root/venv/lib/python3.9/site-packages (2.0.1)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (1.1.2)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (0.4.0)
Requirement already satisfied: termcolor>=1.1.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (2.0.1)
Requirement already satisfied: six>=1.12.0 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (0.27.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: astunparse>=1.6.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.6 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (4.4.0)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (3.19.6)
Requirement already satisfied: google-pasta>=0.1.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: packaging in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from tensorflow) (21.3)
Requirement already satisfied: flatbuffers>=2.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (22.9.24)
Requirement already satisfied: keras<2.11,>=2.10.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: tensorflow-estimator<2.11,>=2.10.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: libclang>=13.0.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (14.0.6)
Requirement already satisfied: tensorboard<2.11,>=2.10 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (2.10.1)
Requirement already satisfied: numpy>=1.20 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (1.23.4)
Requirement already satisfied: absl-py>=1.0.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (1.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (1.50.0)
Requirement already satisfied: h5py>=2.9.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorflow) (3.7.0)
Requirement already satisfied: setuptools in /root/venv/lib/python3.9/site-packages (from tensorflow) (58.1.0)
Requirement already satisfied: dm-tree in /root/venv/lib/python3.9/site-packages (from tensorflow-probability) (0.1.8)
Requirement already satisfied: decorator in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from tensorflow-probability) (5.1.1)
Requirement already satisfied: cloudpickle>=1.3 in /root/venv/lib/python3.9/site-packages (from tensorflow-probability) (3.0.0)
Requirement already satisfied: tabulate>=0.7.5 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from dm-sonnet) (0.9.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.9/site-packages (from astunparse>=1.6.0->tensorflow) (0.40.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorboard<2.11,>=2.10->tensorflow) (1.8.1)
Requirement already satisfied: requests<3,>=2.21.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.28.1)
Requirement already satisfied: markdown>=2.6.8 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorboard<2.11,>=2.10->tensorflow) (3.4.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.21.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorboard<2.11,>=2.10->tensorflow) (0.6.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorboard<2.11,>=2.10->tensorflow) (0.4.6)
Requirement already satisfied: werkzeug>=1.0.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.2.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from packaging->tensorflow) (3.0.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (5.2.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (0.2.8)
Requirement already satisfied: urllib3<2.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (1.26.12)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow) (5.0.0)
Requirement already satisfied: idna<4,>=2.5 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in /shared-libs/python3.9/py-core/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (2022.9.24)
Collecting MarkupSafe>=2.1.1
  Using cached MarkupSafe-2.1.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Requirement already satisfied: zipp>=0.5 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow) (3.9.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow) (3.2.2)
Installing collected packages: MarkupSafe
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 2.0.0
    Not uninstalling markupsafe at /shared-libs/python3.9/py-core/lib/python3.9/site-packages, outside environment /root/venv
    Can't uninstall 'MarkupSafe'. No files were found to uninstall.
Successfully installed MarkupSafe-2.1.3

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: dm-sonnet in /root/venv/lib/python3.9/site-packages (2.0.1)
Requirement already satisfied: wrapt>=1.11.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from dm-sonnet) (1.14.1)
Requirement already satisfied: numpy>=1.16.3 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from dm-sonnet) (1.23.4)
Requirement already satisfied: tabulate>=0.7.5 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from dm-sonnet) (0.9.0)
Requirement already satisfied: dm-tree>=0.1.1 in /root/venv/lib/python3.9/site-packages (from dm-sonnet) (0.1.8)
Requirement already satisfied: absl-py>=0.7.1 in /shared-libs/python3.9/py/lib/python3.9/site-packages (from dm-sonnet) (1.3.0)

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
TensorFlow version 2.10.0
Sonnet version 2.0.1

**Comment by tomhennigan** [comment]
Hi all, this seems like a backwards incompatibility in the latest version of TensorFlow. It is fixed in Sonnet since ee6c95cb598c89ebc2d22264629e5b86b6f7f07a, you can install from head in Colab with:

```python
!pip install git+https://github.com/google-deepmind/sonnet.git
```

Example: https://colab.research.google.com/gist/tomhennigan/5708fee0b1f19b511e27172ef979cce3/example-of-installing-sonnet-from-head.ipynb

I'll look into pushing a new release in the new year so this doesn't keep biting people. Thanks for the heads up.

**Comment by drscotthawley** [comment]
@tomhennigan Thanks for your help!  I confirm that that works for the basic install-check. 


This may be a new Issue but I'll mention it here: My real hope was to to run the [VQ-VAE example](https://github.com/google-deepmind/sonnet/blob/v1/sonnet/examples/vqvae_example.ipynb), which I've been able to update a bit by updating the `tensorflow` calls, e.g. 

```python
#tf.gfile.MakeDirs(local_data_dir)
tf.io.gfile.makedirs(local_data_dir)
```

But it seems that `sonnet` itself suffers from an error for which downgrading `tensorflow` seems unlikely to fix:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-8-d52ca6c4f82a>](https://localhost:8080/#) in <cell line: 20>()
     18   return tf.nn.relu(h)
     19 
---> 20 class Encoder(snt.AbstractModule):
     21   def __init__(self, num_hiddens, num_residual_layers, num_residual_hiddens,
     22                name='encoder'):

AttributeError: module 'sonnet' has no attribute 'AbstractModule'
```

This error was already brought up in Issue #128 , but that Issue is marked Closed and yet I'm seeing in the newest version of `sonnet`. 

Was the example tested for Sonnet 2?   #128  suggests that `AbstractModule` was removed in v. 2. 
Thanks!

**Comment by tomhennigan** [comment]
Hi @drscotthawley , there is a version of the VQ-VAE example updated for Sonnet 2 here: https://github.com/google-deepmind/sonnet/blob/v2/examples/vqvae_example.ipynb

**Comment by drscotthawley** [comment]
@tomhennigan 
Thanks very much for you reply! 

Looks like the notebook you linked to has the same problem as before...

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-2-eb53432bd9f1>](https://localhost:8080/#) in <cell line: 7>()
      7 try:
----> 8   import sonnet.v2 as snt
      9   tf.enable_v2_behavior()

4 frames
ImportError: cannot import name 'context' from 'tensorflow.python' (/usr/local/lib/python3.10/dist-packages/tensorflow/python/__init__.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/sonnet/src/recurrent.py](https://localhost:8080/#) in <module>
     34 # pylint: disable=g-direct-tensorflow-import
     35 # Required for specializing `UnrolledLSTM` per device.
---> 36 from tensorflow.python import context as context_lib
     37 from tensorflow.python.eager import function as function_lib
     38 # pylint: enable=g-direct-tensorflow-import

ImportError: cannot import name 'context' from 'tensorflow.python' (/usr/local/lib/python3.10/dist-packages/tensorflow/python/__init__.py)
```

....But installing from `git` as you recommended earlier fixes it:

```python
#!pip install dm-sonnet dm-tree
!pip install git+https://github.com/google-deepmind/sonnet.git dm-tree
```

Full execution completes via this edited notebook on Colab: https://colab.research.google.com/drive/1jZcQtxEGVzoKLvLVglyRr2pYyZfne10-?usp=sharing

Closing.

**Comment by tomhennigan** [comment]
I've pushed [2.0.2](https://pypi.org/project/dm-sonnet/2.0.2/) which fixes this issue. Thanks!
