### ISSUE TITLE
AttributeError: module 'nest' has no attribute 'Create'

### ISSUE THREAD

**Issue by Dipendra7** [deepmind/sonnet#279]
`import matplotlib.pyplot as plt
import nest
neuron = nest.Create("iaf_psc_alpha")`

AttributeError: module 'nest' has no attribute 'Create'

I am running in colab. 
pip install pynest-api
import sklearn
import scipy

import nest

**Comment by superbobry** [comment]
Hi @Dipendra7, this does not look like a Sonnet issue. Please report a bug/ask a question on the issue tracker of `pynest-api`.
