### ISSUE TITLE
Mac install fails

### ISSUE THREAD

**Issue by SWbrsh31** [deepmind/sonnet#29]
I am trying to install sonnet on Mac but I get the following error: 
sonnet/sonnet/python/BUILD:131:1 C++ compilation of rule '@protobuf//:protobuf' failed: cc_wrapper.sh failed: error executing command 
  (exec env - \
    PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/swarsh/torch/install/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin \
    TMPDIR=/var/folders/q9/1zzwnrpx5f31kw21mwzdqxjh0000gn/T/ \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -MD -MF bazel-out/host/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/struct.pb.d '-frandom-seed=bazel-out/host/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/struct.pb.o' -iquote external/protobuf -iquote bazel-out/host/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/protobuf/src -isystem bazel-out/host/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/protobuf/src/google/protobuf/struct.pb.cc -o bazel-out/host/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/struct.pb.o)

external/local_config_cc/cc_wrapper.sh: line 56: -U_FORTIFY_SOURCE: command not found

**Comment by Shuolongbj** [comment]
tray to reinstall protobuff
https://github.com/google/protobuf

**Comment by Shuolongbj** [comment]
hi,try to git checkout step.good luck

FYI.#23
cd sonnet/tensorflow
git checkout r1.1
./configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
pip uninstall tensorflow
pip install /tmp/tensorflow_pkg/tensorflow-1.1.0-cp27-cp27m-macosx_10_7_x86_64.whl
cd ../
bazel build --config=opt //:install
bazel-bin/install /tmp/sonnet_pkg
pip uninstall sonnet
pip install /tmp/sonnet_pkg/sonnet-1.0-py2-none-any.whl

**Comment by malcolmreynolds** [comment]
Hi @SWbrsh31 - please see https://github.com/deepmind/sonnet/issues/56 - there are preliminary Wheel files available on PyPI. Please try to install and let us know how you get on.

**Comment by kosklain** [comment]
Closed due to inactivity.
