### ISSUE TITLE
[fixed! gcc Incompatible]Bazel build failed on MacOS Sierra(10.12.4) with anaconda3 gcc(4.85) TF(1.1)

### ISSUE THREAD

**Issue by Shuolongbj** [deepmind/sonnet#32]
(sonnet) Ru@bogon:~/sonnet$ bazel build --config=opt :install
WARNING: Config values are not defined in any .rc file: opt
WARNING: /private/var/tmp/_bazel_ru/2ccf39bc8e5cbbbc68b5ae8b2d9c72e9/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /Users/Ru/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc:ops/resampler.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/Ru/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /Users/Ru/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/Ru/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /Users/Ru/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.h' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/Ru/sonnet/sonnet/tensorflow.bzl:108:25.
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_ru/2ccf39bc8e5cbbbc68b5ae8b2d9c72e9/external/protobuf/BUILD:113:1: C++ compilation of rule '@protobuf//:protobuf' failed: Process exited with status 1 [sandboxed].
gcc: error: unrecognized command line option '-Wthread-safety'
gcc: error: unrecognized command line option '-Wself-assign'
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //:install failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.571s, Critical Path: 1.04s

(sonnet) Ru@bogon:~/sonnet$bazel version
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:39:33 2017 (1489671573)
Build timestamp: 1489671573
Build timestamp as int: 1489671573

(sonnet) Ru@bogon:~/sonnet$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/Users/Ru/anaconda/envs/sonnet/bin/../libexec/gcc/x86_64-apple-darwin11.4.2/4.8.5/lto-wrapper
Target: x86_64-apple-darwin11.4.2
Configured with: ./configure --prefix=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-gxx-include-dir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/gcc/include/c++ --bindir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin --datarootdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share --libdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib --with-gmp=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpfr=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpc=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-isl=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-cloog=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-boot-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --with-stage1-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --enable-checking=release --with-tune=generic --disable-multilib
Thread model: posix
gcc version 4.8.5 (GCC)

please help...

@malcolmreynolds @diegolascasas @bfredl 

thank you

**Comment by Shuolongbj** [comment]
so...i recreate the env python2.7(conda create -n sonnet python=2.7) and occurred the same error at the build step. 
WARNING: Config values are not defined in any .rc file: opt
WARNING: /private/var/tmp/_bazel_Ru/2ccf39bc8e5cbbbc68b5ae8b2d9c72e9/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /Users/Ru/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc:ops/resampler.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/Ru/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /Users/Ru/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/Ru/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /Users/Ru/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.h' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/Ru/sonnet/sonnet/tensorflow.bzl:108:25.
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_Ru/2ccf39bc8e5cbbbc68b5ae8b2d9c72e9/external/highwayhash/BUILD.bazel:22:1: C++ compilation of rule '@highwayhash//:arch_specific' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 ... (remaining 29 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: unrecognized command line option '-Wthread-safety'
gcc: error: unrecognized command line option '-Wself-assign'
Target //:install failed to build
Use --verbose_failures to see the command lines of failed build steps.

BTW： is it related to the sip (System Integrity Protection) mechanism of mac os?

**Comment by malcolmreynolds** [comment]
@Shuolongbj can you post what you get when running 'gcc --version' ?

**Comment by Shuolongbj** [comment]
@malcolmreynolds thank you.

(sonnet) Ru@bogon:~/sonnet$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/Users/Ru/anaconda/envs/sonnet/bin/../libexec/gcc/x86_64-apple-darwin11.4.2/4.8.5/lto-wrapper
Target: x86_64-apple-darwin11.4.2
Configured with: ./configure --prefix=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-gxx-include-dir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/gcc/include/c++ --bindir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin --datarootdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share --libdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib --with-gmp=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpfr=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpc=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-isl=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-cloog=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-boot-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --with-stage1-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --enable-checking=release --with-tune=generic --disable-multilib
Thread model: posix
gcc version 4.8.5 (GCC)

**Comment by Shuolongbj** [comment]
(deepmind) Ru@MacBook-Pro:~/sonnet$ bazel build --config=opt //:install --strategy=CppCompile=standalone --verbose_failures
WARNING: Config values are not defined in any .rc file: opt
WARNING: /private/var/tmp/_bazel_longrujun/2ccf39bc8e5cbbbc68b5ae8b2d9c72e9/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /Users/Ru/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc:ops/resampler.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/Ru/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /Users/Ru/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/Ru/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /Users/Ru/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.h' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /Users/Ru/sonnet/sonnet/tensorflow.bzl:108:25.
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_Ru/2ccf39bc8e5cbbbc68b5ae8b2d9c72e9/external/protobuf/BUILD:113:1: C++ compilation of rule '@protobuf//:protobuf' failed: cc_wrapper.sh failed: error executing command
  (cd /private/var/tmp/_bazel_longrujun/2ccf39bc8e5cbbbc68b5ae8b2d9c72e9/execroot/sonnet && \
  exec env - \
    LD_LIBRARY_PATH=:/Users/Ru/Qt5.8.0/5.8/clang_64/lib:/usr/local/Cellar/hdf5/1.10.0-patch1/lib:/usr/lib:/usr/local/lib \
    PATH='/Users/Ru/anaconda/envs/deepmind/bin:/usr/local/opt/libiconv/bin:/usr/local/opt/libxml2/bin:/Users/Ru/anaconda/bin:/usr/local/opt/libxml2/bin:/Users/Ru/anaconda/bin:/usr/local/Cellar/hadoop/2.7.3/bin:/usr/local/Cellar/scala/2.12.1/bin:/usr/local/Cellar/apache-spark/2.1.0/libexec/bin:/Users/Ru/Qt5.8.0/5.8/clang_64/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/php71/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/hadoop/2.7.3/sbin:/usr/local/Cellar/hadoop/2.7.3/bin:/usr/local/Cellar/hadoop/2.7.3/bin:/usr/local/Cellar/scala/2.12.1/bin:/usr/local/Cellar/apache-spark/2.1.0/libexec/bin:.;/Users/Ru/Qt5.8.0/5.8/clang_64/bin:/usr/local/Cellar/libxml2/2.9.4_2/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/php71/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin:/usr/local/Cellar/hadoop/2.7.3/sbin:/usr/local/Cellar/hadoop/2.7.3/bin' \
    TMPDIR=/var/folders/l8/vgdsznqs12l6yxf4tdljm04h0000gn/T/ \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/local-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/map_field.pic.d '-frandom-seed=bazel-out/local-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/map_field.pic.o' -fPIC -iquote external/protobuf -iquote bazel-out/local-fastbuild/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/protobuf/src -isystem bazel-out/local-fastbuild/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/protobuf/src/google/protobuf/map_field.cc -o bazel-out/local-fastbuild/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/map_field.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: unrecognized command line option '-Wthread-safety'
gcc: error: unrecognized command line option '-Wself-assign'
Target //:install failed to build
INFO: Elapsed time: 0.518s, Critical Path: 0.22s

**Comment by malcolmreynolds** [comment]
Can you do: `touch blah.cc && gcc -c -Wthread-safety blah.cc`?

I suspect it will fail for you.. On my Mac (10.12.4) that line completes without an error, most likely because gcc is actually aliased to Clang:

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
I'm not sure why this discrepancy would be there. Do you have XCode installed, and if so what version?

**Comment by Shuolongbj** [comment]
(deepmind) Ru@MacBook-Pro:~/sonnet$ touch blah.cc && gcc -c -Wthread-safety blah.cc
gcc: error: unrecognized command line option ‘-Wthread-safety’
(deepmind) @MacBook-Pro:~/sonnet$ gcc --version
gcc (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

i installed Xcode(8.3.2)

**Comment by Shuolongbj** [comment]
@malcolmreynolds thank you .that is my gcc Incompatible.i uninstall the anaconda envs gcc/libgcc(conda uninstall gcc ,pip uninstall gcc)
and all is ok by the Official installation steps after i reinstalled Command_Line_Tools_macOS_10.12_for_Xcode.

$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

but: 
error 1:
$ pwd
/Users/Ru
$python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sonnet as snt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Ru/anaconda/envs/sonnet/lib/python2.7/site-packages/sonnet/__init__.py", line 103, in <module>
    from sonnet.python.ops.resampler import resampler
  File "/Users/Ru/anaconda/envs/sonnet/lib/python2.7/site-packages/sonnet/python/ops/resampler.py", line 33, in <module>
    tf.resource_loader.get_path_to_datafile("_resampler.so"))
  File "/Users/Ru/anaconda/envs/sonnet/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/Ru/anaconda/envs/sonnet/lib/python2.7/site-packages/sonnet/python/ops/_resampler.so, 6): Symbol not found: __ZN10tensorflow15shape_inference16InferenceContext15WithRankAtLeastENS0_11ShapeHandleEiPS2_
  Referenced from: /Users/Ru/anaconda/envs/sonnet/lib/python2.7/site-packages/sonnet/python/ops/_resampler.so
  Expected in: flat namespace
 in /Users/Ru/anaconda/envs/sonnet/lib/python2.7/site-packages/sonnet/python/ops/_resampler.so

error 2:
$ pwd
/Users/Ru/sonnet
$python
python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sonnet as snt
>>> import tensorflow as tf
>>> snt.resampler(tf.constant([0.]), tf.constant([0.]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sonnet/python/ops/resampler.py", line 65, in resampler
    raise ImportError("_gen_resampler could not be imported.")
ImportError: _gen_resampler could not be imported.
>>> import sonnet as snt
>>> import tensorflow as tf
>>> snt.resampler(tf.constant([0.]), tf.constant([0.]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sonnet/python/ops/resampler.py", line 65, in resampler
    raise ImportError("_gen_resampler could not be imported.")
ImportError: _gen_resampler could not be imported.

**Comment by Shuolongbj** [comment]
(sonnet) Ru@bogon:~/sonnet$ nm /Users/Ru/anaconda/envs/sonnet/lib/python2.7/site-packages/sonnet/python/ops/_resampler.so | grep CheckOpMessageBuilder
0000000000002310 T __ZN10tensorflow8internal21CheckOpMessageBuilder7ForVar1Ev
                 U __ZN10tensorflow8internal21CheckOpMessageBuilder7ForVar2Ev
                 U __ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
                 U __ZN10tensorflow8internal21CheckOpMessageBuilderC1EPKc
                 U __ZN10tensorflow8internal21CheckOpMessageBuilderD1Ev

(sonnet) Ru@bogon:~/sonnet$ nm /Users/Ru/anaconda/envs/sonnet/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so |grep CheckOpMessageBuilder
0000000001dffc50 T __ZN10tensorflow8internal21CheckOpMessageBuilder7ForVar2Ev
0000000001dffc80 T __ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
0000000001dffc00 T __ZN10tensorflow8internal21CheckOpMessageBuilderC1EPKc
0000000001dffad0 T __ZN10tensorflow8internal21CheckOpMessageBuilderC2EPKc
0000000001dffc30 T __ZN10tensorflow8internal21CheckOpMessageBuilderD1Ev
0000000001dffc10 T __ZN10tensorflow8internal21CheckOpMessageBuilderD2Ev

**Comment by Shuolongbj** [comment]
thank you .i reinstall sonnet by #5 and #23 and now is work.

cd sonnet/tensorflow
git checkout r1.1
./configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
sudo -H pip uninstall tensorflow
sudo -H pip install /tmp/tensorflow_pkg/tensorflow-1.1.0rc1-cp27-cp27mu-linux_x86_64.whl
cd ../
bazel build --config=opt //:install
bazel-bin/install /tmp/sonnet_pkg
sudo -H pip uninstall sonnet
sudo -H pip install /tmp/sonnet_pkg/sonnet-1.0-py2-none-any.whl


(sonnet) Ru@bogon:~/sonnet/sonnet/examples$ python rnn_shakespeare_test.py

..
----------------------------------------------------------------------
Ran 2 tests in 557.633s

OK

**Comment by malcolmreynolds** [comment]
@Shuolongbj glad you got it working!
