### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AbstractModule'   when running python train.py in deepmind/dnc

### ISSUE THREAD

**Issue by b03201003** [deepmind/sonnet#33]

**Comment by tfgg** [comment]
Hi there. Could you possibly share your code here? There isn't a train.py in this repository.

**Comment by b03201003** [comment]
https://github.com/deepmind/dnc

I've installed sonnet by using pip install sonnet 
However when I run "python train.py"
I got AttributeError: 'module' object has no attribute 'AbstractModule'
 in addressing py line 58

**Comment by diegolascasas** [comment]
Sonnet is not currently in PyPI, the sonnet package you get from `pip install sonnet` is a package related to NetworkX. Please make sure to install Sonnet following the [installation instructions](https://github.com/deepmind/sonnet#installation-instructions).

**Comment by b03201003** [comment]
Thanks a lot!
The installation is done!
