### ISSUE TITLE
Problem installing sonnet on a GPU machine

### ISSUE THREAD

**Issue by parunach** [deepmind/sonnet#34]
I have a CUDA supported CentOS 7 GPU machine with TF version 1.1.0 and tried to install sonnet

When I run 

`./configure`

I get

`ERROR: /home/xbbl35h/code/sonnet/tensorflow/WORKSPACE:3:1: //external:io_bazel_rules_closure: no such attribute 'urls' in 'http_archive' rule.
ERROR: /home/xbbl35h/code/sonnet/tensorflow/WORKSPACE:3:1: //external:io_bazel_rules_closure: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package.
`

I saw that someone had posted a change and I have the WORKSPACE file changed to

```
http_file(
  name = "weblas_weblas_js",
  url = "file:///local_path/weblas.js",
)

```
I suspect it is something simple

**Comment by diegolascasas** [comment]
Hi there.
What version of bazel do you have?
`bazel version` will tell you that.

**Comment by parunach** [comment]
It looks like the latest version fixed this. Closing.
