### ISSUE TITLE
Bazel build failure on Ubuntu14.04

### ISSUE THREAD

**Issue by Jieeee** [deepmind/sonnet#37]
(tensorflow-1.0.1)sj@vipa-Precision-Tower-7910:~/software/sonnet$ bazel build --strategy=CppCompile=standalone --verbose_failures --config=opt :install
WARNING: Config values are not defined in any .rc file: opt
WARNING: /home/sj/.cache/bazel/_bazel_sj/be13dc62f2ab4b36343926cedc20e2d6/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /home/sj/software/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc:ops/resampler.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /home/sj/software/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /home/sj/software/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /home/sj/software/sonnet/sonnet/tensorflow.bzl:108:25.
WARNING: /home/sj/software/sonnet/sonnet/python/BUILD:127:1: in srcs attribute of cc_binary rule //sonnet/python:ops/_resampler.so: please do not import '//sonnet/cc/kernels:resampler_op.h' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_custom_op_library', the error might have been caused by the macro implementation in /home/sj/software/sonnet/sonnet/tensorflow.bzl:108:25.
INFO: Found 1 target...
ERROR: /home/sj/.cache/bazel/_bazel_sj/be13dc62f2ab4b36343926cedc20e2d6/external/org_tensorflow/tensorflow/core/BUILD:1150:1: C++ compilation of rule '@org_tensorflow//tensorflow/core:lib_internal' failed: gcc failed: error executing command 
  (cd /home/sj/.cache/bazel/_bazel_sj/be13dc62f2ab4b36343926cedc20e2d6/execroot/sonnet && \
  exec env - \
    LD_LIBRARY_PATH=/home/sj/software/opencv_2.4.9/lib/:/usr/local/cuda-8.0/lib64 \
    PATH=/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -MD -MF bazel-out/host/bin/external/org_tensorflow/tensorflow/core/_objs/lib_internal/external/org_tensorflow/tensorflow/core/lib/strings/str_util.d '-frandom-seed=bazel-out/host/bin/external/org_tensorflow/tensorflow/core/_objs/lib_internal/external/org_tensorflow/tensorflow/core/lib/strings/str_util.o' -DEIGEN_MPL2_ONLY -iquote external/org_tensorflow -iquote bazel-out/host/genfiles/external/org_tensorflow -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -iquote external/protobuf -iquote bazel-out/host/genfiles/external/protobuf -iquote external/eigen_archive -iquote bazel-out/host/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/host/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/host/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/host/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/host/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/host/genfiles/external/farmhash_archive -iquote external/highwayhash -iquote bazel-out/host/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/host/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/protobuf/src -isystem bazel-out/host/genfiles/external/protobuf/src -isystem external/eigen_archive -isystem bazel-out/host/genfiles/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/host/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/host/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/host/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions -msse3 -pthread -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_tensorflow/tensorflow/core/lib/strings/str_util.cc -o bazel-out/host/bin/external/org_tensorflow/tensorflow/core/_objs/lib_internal/external/org_tensorflow/tensorflow/core/lib/strings/str_util.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from external/org_tensorflow/tensorflow/core/lib/gtl/array_slice.h:101:0,
                 from external/org_tensorflow/tensorflow/core/lib/strings/str_util.h:23,
                 from external/org_tensorflow/tensorflow/core/lib/strings/str_util.cc:16:
external/org_tensorflow/tensorflow/core/lib/gtl/array_slice_internal.h:232:38: error: 'tensorflow::gtl::array_slice_internal::ArraySliceImplBase<const T>::ArraySliceImplBase' names constructor
external/org_tensorflow/tensorflow/core/lib/gtl/array_slice_internal.h:252:32: error: 'tensorflow::gtl::array_slice_internal::ArraySliceImplBase<T>::ArraySliceImplBase' names constructor
In file included from external/org_tensorflow/tensorflow/core/lib/gtl/array_slice.h:102:0,
                 from external/org_tensorflow/tensorflow/core/lib/strings/str_util.h:23,
                 from external/org_tensorflow/tensorflow/core/lib/strings/str_util.cc:16:
external/org_tensorflow/tensorflow/core/lib/gtl/inlined_vector.h: In member function 'void tensorflow::gtl::InlinedVector<T, N>::Destroy(T*, int)':
external/org_tensorflow/tensorflow/core/lib/gtl/inlined_vector.h:396:10: error: 'is_trivially_destructible' is not a member of 'std'
external/org_tensorflow/tensorflow/core/lib/gtl/inlined_vector.h:396:42: error: expected primary-expression before '>' token
external/org_tensorflow/tensorflow/core/lib/gtl/inlined_vector.h:396:43: error: '::value' has not been declared
Target //:install failed to build
INFO: Elapsed time: 2.086s, Critical Path: 1.43s

**Comment by Shuolongbj** [comment]
Try several times or switch the version(git checkout r1.1 or r1.2).FYI.#5,#23

**Comment by kosklain** [comment]
@Jieeee can you confirm that the above solution solves your problem?

**Comment by kosklain** [comment]
Closed due to inactivity. Please reopen if the solution doesn't solve your problem.
