### ISSUE TITLE
Anyone successfully call snt.ConvLSTM?

### ISSUE THREAD

**Issue by leesunfreshing** [deepmind/sonnet#38]
I assume it only requires the code like:
convlstm = snt.ConvLSTM() to call, but fails and prompting no such module...

**Comment by diegolascasas** [comment]
Did you mean `snt.Conv1DLSTM`?

**Comment by leesunfreshing** [comment]
I have tried snt.Conv1DLSTM, snt.Conv2DLSTM and snt.ConvLSTM, none of those works... is that one works for you? @diegolascasas

**Comment by malcolmreynolds** [comment]
We missed out exposing this in __init__.py so it's not accessible directly under snt, but you should be able to get to it manually with `snt.python.modules.gated_rnn.ConvLSTM`. We'll fix this ASAP.

**Comment by diegolascasas** [comment]
Hi @leesunfreshing,
Can you pull the recent changes and check whether the issue persists?
`snt.Conv1DLSTM`, `snt.Conv1DLSTM` and `snt.python.modules.gated_rnn.ConvLSTM` should be available.

**Comment by diegolascasas** [comment]
Closed due to inactivity.
