### ISSUE TITLE
issue installing sonnet on on tensorflow rc1.2 using compiled from source installation

### ISSUE THREAD

**Issue by outcastofmusic** [deepmind/sonnet#40]
Hi, 
I am trying to install sonnet on top of tensorflow rc1.2 and get the following error: 
` /root/.cache/bazel/_bazel_root/76ab1f57e69b3872947e0ef757e4f315/external/org_tensorflow/tensorflow/workspace.bzl:7:6: file '@io_bazel_rules_closure//closure:defs.bzl' does not contain symbol 'web_library_external'.`

I'm doing it in a docker image with Ubuntu 16:04 and Python 3.5
here is a [link](https://github.com/outcastofmusic/docker-research-images/blob/master/compiled-r12/Dockerfile) to a docker file replicating the issue
Using a similar DockerFile which uses tensorflow r1.1 in this [link](https://github.com/outcastofmusic/docker-research-images/blob/master/compiled-r11/Dockerfile) everything works fine.

**Comment by diegolascasas** [comment]
Hello, thanks for reporting the issue.

This is due to a workaround that is needed to keep Tensorflow as a dependency. We will update our code to reflect the recent changes in the Tensorflow repository, which will eliminate this issue, but for now you can edit Sonnet's WORKSPACE file and change the `http_archive` entry to the following: 

```
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "60fc6977908f999b23ca65698c2bb70213403824a84f7904310b6000d78be9ce",
    strip_prefix = "rules_closure-5ca1dab6df9ad02050f7ba4e816407f88690cf7d",
    urls = [
        "http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz",  # 2017-02-03
        "https://github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz",
    ],
)
```

Does this solve your problem?

**Comment by diegolascasas** [comment]
Note: Edited my previous comment to correct the change.

**Comment by outcastofmusic** [comment]
Hi, thanks for the explanation. Wrote a little script that changes the sonnet workspace based on the tensorflow workspace and everything installs fine now.

**Comment by diegolascasas** [comment]
Great, I'll close the issue then. Feel free to reopen if you find any problem.
