### ISSUE TITLE
I am trying to get sonnet installed I like the idea of some of the configure features but i would like a little more documentation on getting the full featured configured sonnet

### ISSUE THREAD

**Issue by josheeg** [deepmind/sonnet#41]
I am trying to get sonnet installed I like the idea of some of the configure features but i would like a little more documentation on getting the full featured configured sonnet.

OpenCL and if I can get the ANN in a FPGA would be a great tutorial.

Video tutorials could help cover details. 

There are free screencasting linux and windows software.

**Comment by malcolmreynolds** [comment]
@josheeg thanks for your interest. To clarify, Sonnet is a higher level framework on top on TensorFlow, so device assignments like OpenCL or FPGA are orthogonal to what Sonnet lets you do. If and when they are supported by TensorFlow, you will be able to use Sonnet modules (containing supported ops) on those devices.

We don't have the engineering bandwidth currently to produce anything like video tutorials (no one works on Sonnet full time, it's all best-effort by people who are primarily on other projects). The rnn_shakespeare example is intended to showcase some of the main features. We'll look into providing more in the future.
