### ISSUE TITLE
Could a DVD Ubuntu image with all of the things installed or something make this easy to use?

### ISSUE THREAD

**Issue by josheeg** [deepmind/sonnet#43]
image with all of the things installed or something make this easy to use?
I see there is a virtual environment are there images of that or something that could make a CPU version of this available and then a user could put the code they write to Amazon ec2 cloud running GPUs?

**Comment by zhangshengshan** [comment]
Maybe a docker image will be a good option!

**Comment by malcolmreynolds** [comment]
We don't use Docker internally so we won't be able to add an officially supported Docker image to the main repository. There is a Python 3 Docker image here: https://hub.docker.com/r/smizy/sonnet/ which looks like it might suit your needs.

**Comment by malcolmreynolds** [comment]
Another Docker image including Sonnet is [Deepo](https://github.com/ufoym/deepo). Closing this, as I think there are a bunch of externally supported possibilities.
