### ISSUE TITLE
Run Sonnet on Google Cloud ML

### ISSUE THREAD

**Issue by afhuertass** [deepmind/sonnet#46]
Hi.

More than an issue, my question is if there is some easy way to run sonnet on Google Cloud Machine Learning,  i have a code i would like to test on the cloud but is written using Sonnet and i get an import error trying to run it. 
Maybe using the setup.py but i'm new building packages and nothing comes to my mind. 

If this isn't the place for this question, I apologize. 

Any help on this matter is really appreciated. 
Thanks

**Comment by Shuolongbj** [comment]
FYI.
Google Cloud ML Engine already has an optimized and GPU-enabled TensorFlow version installed.  you could remove the tensorflow line from setup.py to make it work,or the GPU not being used if you download the CPU-only tensorflow package from PyPI and shadowing the existing TensorFlow installation.

**Comment by afhuertass** [comment]
@Shuolongbj  Hi, i make Sonnet work on google Cloud after a while, i did it by compiling the library on my machine, upload the wheel file to Google Cloud Storage, and specifying the --package option when uploading the job. 

After a while I came to realize that the trainign was going slow, so I started to think that the gpu was not being used. what i think,  needs to be done is recompiling the sonnet library against a GPU supported Tensorflow, and it maybe work fine in that case.

Thanks for your answer. :)

**Comment by diegolascasas** [comment]
Hi @afhuertass,

Sonnet should be using the version of tensorflow you installed with pip. 

Do you get only CPU devices when you run a session with device placement being logged?
([see here](https://www.tensorflow.org/tutorials/using_gpu))

And do you get GPU devices when you run tensorflow ops without Sonnet?

**Comment by malcolmreynolds** [comment]
@afhuertass Can you try installing the pip package (either 'dm-sonnet' or 'dm-sonnet-gpu') ?

**Comment by diegolascasas** [comment]
Closed due to inactivity. Feel free to reopen the bug if you have any problem installing from pip.
