### ISSUE TITLE
AttributeError: 'module' object has no attribute 'reuse_variables'

### ISSUE THREAD

**Issue by jontoto** [deepmind/sonnet#47]
Not quite sure why I'm getting this error. Does it have something to do with reuse_variables still being experimental? 

Thanks

**Comment by diegolascasas** [comment]
Hi jontoto,

`reuse_variables` was recently moved from `experimental` to `utils`.
Can you provide a bit more context on how you are getting this error?
Maybe a reproducible code snippet or a stack trace.
Also, can you confirm you are using version 1.3?

**Comment by jontoto** [comment]
I missed the update and was trying to use the docs for the newer version, my mistake.

Thanks for the help!
