### ISSUE TITLE
$ ./bazel-bin/install   needs absolute path

### ISSUE THREAD

**Issue by githuboml** [deepmind/sonnet#48]
Ahoi!

I installed sonnet according to the readme, but I was stuck quite some time at this point:

$ ./bazel-bin/install /tmp/sonnet

I replaced /tmp/sonnet by some local relative directory path, which doesnt work, i.e. no .whl is generated. If I use ./bazel-bin/install with some absolute path everything works fine (read: breaks at another point).

I first thought that was a bazel issue, but some guys in the #bazel channel on irc convinced me otherwise.
I recommend either fixing the handling of relative paths in the ./bazel-bin/install script itself, throwing an error or at least pointing out the issue in the README.md. That way others may not be stuck for several hours, too.

**Comment by malcolmreynolds** [comment]
@githuboml thanks for the suggestion - this is now fixed in our internal repository, and will be part of the version we push to GitHub next week.

**Comment by githuboml** [comment]
that was quick. thanks :)
