### ISSUE TITLE
is there a pip install package

### ISSUE THREAD

**Issue by loveJasmine** [deepmind/sonnet#56]

**Comment by malcolmreynolds** [comment]
Hi @loveJasmine - we've got some preliminary wheel files up on PyPI as of today. The package names are "dm-sonnet" or "dm-sonnet-gpu" depending on whether you have tensorflow or tensorflow-gpu installed.

We will change the readme next week to indicate that is the recommended installation procedure, but in the meantime could you try `pip install dm-sonnet` or `pip install dm-sonnet-gpu` and let us know how you get on.

**Comment by loveJasmine** [comment]
not very well, it crashed on dnc project

(venv) mldl@mldlUB1604:~/ub16_prj/dnc-deepmind/sonnet$ python ../train.py --memory_size=64 --num_bits=8 --max_length=3
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "../train.py", line 22, in <module>
    import sonnet as snt
  File "/home/mldl/ub16_prj/dnc-deepmind/sonnet/sonnet/__init__.py", line 40, in <module>
    from sonnet.python.modules import nets
  File "/home/mldl/ub16_prj/dnc-deepmind/sonnet/sonnet/python/modules/nets/__init__.py", line 22, in <module>
    from sonnet.python.modules.nets.alexnet import AlexNet
  File "/home/mldl/ub16_prj/dnc-deepmind/sonnet/sonnet/python/modules/nets/alexnet.py", line 36, in <module>
    from sonnet.python.modules import basic
  File "/home/mldl/ub16_prj/dnc-deepmind/sonnet/sonnet/python/modules/basic.py", line 33, in <module>
    from sonnet.python.ops import nest
  File "/home/mldl/ub16_prj/dnc-deepmind/sonnet/sonnet/python/ops/nest.py", line 41, in <module>
    map = nest.map_structure  # pylint: disable=redefined-builtin
AttributeError: 'module' object has no attribute 'map_structure'
(venv) mldl@mldlUB1604:~/ub16_prj/dnc-deepmind/sonnet$

**Comment by loveJasmine** [comment]
but I also got the same issue as 

Mac install fails #29
Open
I herd results build from source but that could be more problems #42
Open
_resampler.so: undefined symbol #25

**Comment by loveJasmine** [comment]
more seriously, even I build who package from source for Mac, I still got:

ali-186590cc37a5:dnc-deepmind yike.ke$ python train.py 
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    import sonnet as snt
  File "/Library/Python/2.7/site-packages/sonnet/__init__.py", line 126, in <module>
    from sonnet.python.ops.resampler import resampler
  File "/Library/Python/2.7/site-packages/sonnet/python/ops/resampler.py", line 33, in <module>
    tf.resource_loader.get_path_to_datafile("_resampler.so"))
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Library/Python/2.7/site-packages/sonnet/python/ops/_resampler.so, 6): Symbol not found: __ZN10tensorflow15shape_inference16InferenceContext15WithRankAtLeastENS0_11ShapeHandleExPS2_
  Referenced from: /Library/Python/2.7/site-packages/sonnet/python/ops/_resampler.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/sonnet/python/ops/_resampler.so
ali-186590cc37a5:dnc-deepmind yike.ke$

**Comment by TobyPDE** [comment]
Could you please run the following command that prints the TF version and report the output here?

`$ python -c 'import tensorflow as tf; print(tf.__version__)'`

**Comment by loveJasmine** [comment]
oh, I forgot I shift to tf1.1 for another project.

sure, it works well with tf1.2
