### ISSUE TITLE
pip3: Could not find a version that satisfies the requirement dm-sonnet-gpu

### ISSUE THREAD

**Issue by guillaume-chevalier** [deepmind/sonnet#57]
```
$ sudo -H pip3 install dm-sonnet-gpu
Collecting dm-sonnet-gpu
  Could not find a version that satisfies the requirement dm-sonnet-gpu (from versions: )
No matching distribution found for dm-sonnet-gpu
```

**Comment by malcolmreynolds** [comment]
Are you on Mac or Linux? We only provide pre built wheels for the GPU version in Linux, as there are no official tensorflow-gpu packages for Mac & GPU.

**Comment by auroua** [comment]
Encounter the same problem. 
os: Ubuntu 16.04
python: 3.5.2

**Comment by malcolmreynolds** [comment]
The PyPI packages are only built for python 2.7 and 3.4... I'll look into providing packages for 3.{5,6} as well.

**Comment by auroua** [comment]
@malcolmreynolds 
thanks

**Comment by malcolmreynolds** [comment]
@auroua @guillaume-chevalier PyPI should now have packages for python {2.7, 3.4, 3.5, 3.6} - I'm closing this now, please reopen if you have problems.

**Comment by auroua** [comment]
Thanks @malcolmreynolds

**Comment by guillaume-chevalier** [comment]
@malcolmreynolds: Great!
By the way, I was on linux like @auroua. I'm glad to see this issue is resolved!
