### ISSUE TITLE
Issue during install package with pip

### ISSUE THREAD

**Issue by EnricoBeltramo** [deepmind/sonnet#58]
I have follow error when try to install Sonnet:

>pip install dm-sonnet
Collecting dm-sonnet
  Could not find a version that satisfies the requirement dm-sonnet (from versions: )
No matching distribution found for dm-sonnet

I use Windows10 and Tensorflow with GPU version 1.2.1

**Comment by diegolascasas** [comment]
Hi @EnricoBeltramo, 
Windows is currently not supported, but you can try building Sonnet from source following our [installing from source](https://deepmind.github.io/sonnet/#installing-from-source) instructions.  Note that you will probably need to adapt the commands to make them work on Windows, though.

**Comment by EnricoBeltramo** [comment]
Thank you very much: I'll try to build from source

**Comment by malcolmreynolds** [comment]
@EnricoBeltramo if you have trouble building from source, the next version we release will have no C++ inside the wheel file, so should be easily installable on Windows. Most likely ETA is next week sometime.
