### ISSUE TITLE
pondering rnn occured some error when using regularizer

### ISSUE THREAD

**Issue by AlphaSmartDog** [deepmind/sonnet#59]
When I used pondering_rnn (Adaptive Computation Time) to wrap an LSTM cell and tried to use L2 regularization, there were some errors,

```
        initializer = {'b_gates':tf.truncated_normal_initializer(stddev=1.0), 
                       'w_gates':tf.truncated_normal_initializer(stddev=1.0)}
        regularizer = {'b_gates':tf.contrib.layers.l2_regularizer(0.1), 
                       'w_gates':tf.contrib.layers.l2_regularizer(0.1)}
        
        act_core = LSTM(hidden_size, regularizers=regularizer, initializers=initializer)
        self._controller = ACTCore(core=act_core, 
                                   output_size=self._out_width, 
                                   threshold=threshold, 
                                   get_state_for_halting=self._get_hidden_state)
        
        self._initial_state = self._controller.initial_state(self._batch_size)
        regularization_loss = tf.reduce_sum(tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES))
```

The error is as follows:

The node 'Sum' has inputs from different frames. The input 'Sum/input' is in frame 'rnn/while/act_core/while/rnn/while/act_core/while/'. The input 'range' is in frame ''.

Seems to be tf.while_loop the problem, but I do not know how to solve this problem

Young

**Comment by AlphaSmartDog** [comment]
This is the original file I encountered the wrong

**Comment by AlphaSmartDog** [comment]
The prompt error is

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1326     try:
-> 1327       return fn(*args)
   1328     except errors.OpError as e:

E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1305                                    feed_dict, fetch_list, target_list,
-> 1306                                    status, run_metadata)
   1307 

E:\Anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
     88             try:
---> 89                 next(self.gen)
     90             except StopIteration:

E:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py in raise_exception_on_not_ok_status()
    465           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 466           pywrap_tensorflow.TF_GetCode(status))
    467   finally:

InvalidArgumentError: The node 'Sum' has inputs from different frames. The input 'Sum/input' is in frame 'rnn/while/act_core/while/rnn/while/act_core/while/'. The input 'range' is in frame ''.

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-82ae56723932> in <module>()
    131 a = test()
    132 
--> 133 a.fit(batch_x, batch_y)

<ipython-input-1-82ae56723932> in fit(self, x, y)
    121             sess.run(tf.global_variables_initializer())
    122             for i in np.arange(10):
--> 123                 _,a = sess.run([self._train_step, self._cost], feed_dict={self._inputs: x, self._targets: y})
    124                 print (a)
    125 

E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    893     try:
    894       result = self._run(None, fetches, feed_dict, options_ptr,
--> 895                          run_metadata_ptr)
    896       if run_metadata:
    897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1122     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1123       results = self._do_run(handle, final_targets, final_fetches,
-> 1124                              feed_dict_tensor, options, run_metadata)
   1125     else:
   1126       results = []

E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1319     if handle is None:
   1320       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1321                            options, run_metadata)
   1322     else:
   1323       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

E:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1338         except KeyError:
   1339           pass
-> 1340       raise type(e)(node_def, op, message)
   1341 
   1342   def _extend_graph(self):

InvalidArgumentError: The node 'Sum' has inputs from different frames. The input 'Sum/input' is in frame 'rnn/while/act_core/while/rnn/while/act_core/while/'. The input 'range' is in frame ''.

**Comment by jacobmenick** [comment]
What happens if you remove the regularization loss?

**Comment by AlphaSmartDog** [comment]
This problem has been solved
Thanks
