### ISSUE TITLE
Custom Sonnet module fails to merit device placement

### ISSUE THREAD

**Issue by mingyr** [deepmind/sonnet#61]
Recently I try to write some customized python modules based on Sonnet for processing EEG data, but due to the magnitude of EEG data, I want to utilize multiple GPUs for training, then problem emerges that I cannot figure it out.

According to my understanding, the paradigm for synchronous multi-GPU training requires the trainable variables resides on CPU, while operations are performed on GPU, and tensors are transported in between as required.

The problem is in my view such an arrangement is difficult for the Sonnet module. For example, considering the small module as follows:

```
import tensorflow as tf
import sonnet as snt

class RCNNOutput(snt.AbstractModule):
    def __init__(self, out_size, device_name, name = "rcnn_output"):
        super(RCNNOutput, self).__init__(name = name)
        with self._enter_variable_scope():
            with tf.device(device_name):
                bf = snt.BatchFlatten(name = "bf")
                fc0 = snt.Linear(output_size = 256, name = "fc0")
                fc1 = snt.Linear(output_size = out_size, name = "fc1")
                self._seq = snt.Sequential([bf, fc0, tf.nn.relu, fc1], name = "seq")

    def _build(self, inputs):
        return self._seq(inputs)

def test():
    import numpy as np

    rcnn_output = RCNNOutput(4, '/cpu:0')

    with tf.device('/cpu:0'):
        t = tf.constant(np.ones([8, 32, 32, 3]), np.float32)

    with tf.device('/gpu:0'):
        outputs = rcnn_output(t)

    writer = tf.summary.FileWriter("rcnn_output_output", tf.get_default_graph())

    config = tf.ConfigProto(log_device_placement = True)

    with tf.Session(config = config) as sess:
        sess.run([tf.global_variables_initializer(), tf.local_variables_initializer()])

        v = sess.run(outputs)
        print(v)

    writer.close()

if __name__ == "__main__":
    test()

```

whatever I tried, I cannot get the weights put on CPU, it always put on GPU, even I explicitly give the placement directive:

2017-08-31 21:51:11.250360: I tensorflow/core/common_runtime/simple_placer.cc:847] rcnn_output/fc1/b: (VariableV2)/job:localhost/replica:0/task:0/gpu:0
rcnn_output/fc1/b/read: (Identity): /job:localhost/replica:0/task:0/gpu:0
2017-08-31 21:51:11.250366: I tensorflow/core/common_runtime/simple_placer.cc:847] rcnn_output/fc1/b/read: (Identity)/job:localhost/replica:0/task:0/gpu:0
rcnn_output/fc1/b/Assign: (Assign): /job:localhost/replica:0/task:0/gpu:0
2017-08-31 21:51:11.250371: I tensorflow/core/common_runtime/simple_placer.cc:847] rcnn_output/fc1/b/Assign: (Assign)/job:localhost/replica:0/task:0/gpu:0
rcnn_output/fc1/w: (VariableV2): /job:localhost/replica:0/task:0/gpu:0
2017-08-31 21:51:11.250377: I tensorflow/core/common_runtime/simple_placer.cc:847] rcnn_output/fc1/w: (VariableV2)/job:localhost/replica:0/task:0/gpu:0
rcnn_output/fc1/w/read: (Identity): /job:localhost/replica:0/task:0/gpu:0

Only the constant tensor got put on CPU:
Const: (Const): /job:localhost/replica:0/task:0/cpu:0
2017-08-31 21:51:11.250690: I tensorflow/core/common_runtime/simple_placer.cc:847] Const: (Const)/job:localhost/replica:0/task:0/cpu:0

I sincerely appreciate if any engineer at Deepmind could look into the problem and many thanks for giving some suggestions.

**Comment by mingyr** [comment]
Hi,
Based on the latest check in of Sonnet, I have figured out a pretty ugly way of doing, but it is far from the solution, isn't it?

`import tensorflow as tf
import sonnet as snt

class RCNNOutput(snt.AbstractModule):
    def __init__(self, out_size, custom_getter = None, name = "rcnn_output"):
        super(RCNNOutput, self).__init__(custom_getter = custom_getter, name = name)
        with self._enter_variable_scope():
            bf = snt.BatchFlatten(name = "bf")
            fc0 = snt.Linear(output_size = 256, custom_getter = custom_getter, name = "fc0")
            fc1 = snt.Linear(output_size = out_size, custom_getter = custom_getter, name = "fc1")
            self._seq = snt.Sequential([bf, fc0, tf.nn.relu, fc1], name = "seq")

    def _build(self, inputs):
        return self._seq(inputs)

def test():
    import numpy as np

    def cpu_placement(getter, name, *args, **kwargs):
        with tf.device('/cpu:0'):
            return getter(name, *args, **kwargs)

    rcnn_output = RCNNOutput(4, custom_getter = cpu_placement)

    with tf.device('/cpu:0'):
        t = tf.constant(np.ones([8, 32, 32, 3]), np.float32)

    with tf.device('/gpu:0'):
        outputs = rcnn_output(t)

    writer = tf.summary.FileWriter("rcnn_output_output", tf.get_default_graph())

    config = tf.ConfigProto(log_device_placement = True)

    with tf.Session(config = config) as sess:
        sess.run([tf.global_variables_initializer(), tf.local_variables_initializer()])

        v = sess.run(outputs)
        print(v)

    writer.close()

if __name__ == "__main__":
    test()
`

**Comment by kosklain** [comment]
Hey, thanks for raising this. The cleanest way to do this would be using the fact that `tf.device` accepts a `lambda`. Using that lambda you can make variables belong to cpu and the rest to gpu. An example of those kinds of lambda functions can be found at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/device_setter.py (basically you need to distinguish between `Variable` ops and the rest). There should probably be a function like that already, (feel free to submit a PR to TF if you think that would be useful :) ).

**Comment by mingyr** [comment]
Hi, Kosklain:

Sincerely appreciate your respond and your suggestion.

However, it seems still not work for me when I take your suggestion. If it is feasible, could you please give a little demo of your idea? I am not quite sure I understand it correctly and thoroughly. Great thanks.

Check the following code and pay attention to test2, the lambda works for tf.constant but not for Sonnet module:

```
import sonnet as snt

class RCNNOutput(snt.AbstractModule):
    def __init__(self, out_size, custom_getter = None, name = "rcnn_output"):
        super(RCNNOutput, self).__init__(custom_getter = custom_getter, name = name)
        with self._enter_variable_scope():
            bf = snt.BatchFlatten(name = "bf")
            fc0 = snt.Linear(output_size = 256, custom_getter = custom_getter, name = "fc0")
            fc1 = snt.Linear(output_size = out_size, custom_getter = custom_getter, name = "fc1")
            self._seq = snt.Sequential([bf, fc0, tf.nn.relu, fc1], name = "seq")

    def _build(self, inputs):
        return self._seq(inputs)

def test():
    import numpy as np

    def cpu_placement(getter, name, *args, **kwargs):
        with tf.device('/cpu:0'):
            return getter(name, *args, **kwargs)

    rcnn_output = RCNNOutput(4, custom_getter = cpu_placement)

    with tf.device('/cpu:0'):
        t = tf.constant(np.ones([8, 32, 32, 3]), np.float32)

    with tf.device('/gpu:0'):
        outputs = rcnn_output(t)

    writer = tf.summary.FileWriter("rcnn_output_output", tf.get_default_graph())

    config = tf.ConfigProto(log_device_placement = True)

    with tf.Session(config = config) as sess:
        sess.run([tf.global_variables_initializer(), tf.local_variables_initializer()])

        v = sess.run(outputs)
        print(v)

    writer.close()
def test2():
    import numpy as np

    with tf.device(lambda op: '/cpu:0'):
        rcnn_output = RCNNOutput(4)

    with tf.device(lambda op: '/gpu:0'):
        t = tf.constant(np.ones([8, 32, 32, 3]), np.float32)

    with tf.device('/gpu:0'):
        outputs = rcnn_output(t)

    writer = tf.summary.FileWriter("rcnn_output_output", tf.get_default_graph())

    config = tf.ConfigProto(log_device_placement = True)

    with tf.Session(config = config) as sess:
        sess.run([tf.global_variables_initializer(), tf.local_variables_initializer()])

        v = sess.run(outputs)
        print(v)

    writer.close()

if __name__ == "__main__":
    test2()

```

**Comment by kosklain** [comment]
Hi,

Following the code in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/device_setter.py 
your function should distinguish the `op`s  it should put on gpu and the ones it should put on cpu. For example, to put variables on cpu and all the other ops on gpu, you should be able to do the following:

```python
from tensorflow.core.framework import node_def_pb2

[...]
def device_setter(op):
  _variable_ops = ["Variable", "VariableV2", "VarHandleOp"]
  node_def = op if isinstance(op, node_def_pb2.NodeDef) else op.node_def
  return  '/cpu:0' if node_def.op in _variable_ops else '/gpu:0'
[...]   

with tf.device(device_setter):
  outputs = rcnn_output(t)
```

Please let me know if anything is unclear.

**Comment by mingyr** [comment]
Hi, Kosklain:

Great thanks for your feedback and help. It works. I would think you have explained everything crystal clear.

By the way, I did buy several books on TensorFlow, however I would think the author are just focusing on how to use it. I just wonder could you please kindly refer me to some material or books I can get a deeper understanding of TensorFlow?  I know it is irrelevant to this thread, but if you could, I am sincerely appreciating it.

Have a nice weekend.
