### ISSUE TITLE
Bugs with the documentation and example code in Sonnet from DeepMInd

### ISSUE THREAD

**Issue by shyamalschandra** [deepmind/sonnet#62]
```python
import sonnet as snt

train_data = get_training_data()
test_data = get_test_data()

# Construct the module, providing any configuration necessary.
linear_regression_module = snt.Linear(output_size=FLAGS.output_size)

# Connect the module to some inputs, any number of times.
train_predictions = linear_regression_module(train_data)
test_predictions = linear_regression_module(test_data)

```
get_training_data() doesn't work and nor does the get_test_data() functions respectively. 

Also, there is no documentation on how to run the examples with the Shakespeare dataset in /sonnet/sonnet/examples.

Finally, I had to comment the following lines in the source code of Sonnet in lines 42-44 of nest.py inside /sonnet/sonnet/python/ops/:
```python
#map_up_to = nest.map_structure_up_to
#assert_shallow_structure = nest.assert_shallow_structure
#flatten_up_to = nest.flatten_up_to
```
for the code to run.

Could you please let me know if the current version of Sonnet is compatible with Tensorflow 1.3.0?

**Comment by mingyr** [comment]
I would think the code train_data = get_training_data() is a demo that how you can acquire your input data, no guarantee such a function must exist and it should work.

I think  Sonnet is compatible with Tensorflow 1.3.0 since I build everything from scratch and it works fine.

For other questions, left to be answered by engineers from Deepmind. Maybe a model repo like TensorFlow could also be considered to setup for easy of use.

**Comment by diegolascasas** [comment]
Hi @shyamalschandra,

As @mingyr said, the code in the main `README` is there for demonstration purposes and is not runnable, and Sonnet is compatible (and in fact requires) Tensorflow 1.3.

You should not need to comment out these lines of code. Could you post more information, like the error message, version of Tensorflow, Sonnet and Python you are using?

You should be able to run the examples as regular Python scripts:

```sh
python  rnn_shakespeare.py
python  module_with_build_args.py
```

Although it is advisable that you read the code, which is a runnable demonstration on how you can work with Sonnet modules.

Note that you can also run them as Bazel binaries:

```sh
bazel run :rnn_shakespeare 
bazel run :module_with_build_args
```

which will rebuild Sonnet if needed and might be useful if you want to make modifications to the library code.

**Comment by diegolascasas** [comment]
Closed due to inactivity.
