### ISSUE TITLE
The current version does not support Windows?

### ISSUE THREAD

**Issue by shushan2017** [deepmind/sonnet#63]
I used to===   pip install dm-sonnet-gpu 

It can be installed, but testing a DNC program is wrong

**Comment by malcolmreynolds** [comment]
@shushan2017 We don't officially support Windows, although now that the PyPI packages don't contain any C++ (and neither does DNC) this should work. Could you post the error message you receive along with a full backtrace?

**Comment by shushan2017** [comment]
@malcolmreynolds  thanks!!!!!
My environment is： win7(64bit) Anaconda3 (64-bit) python3.6(64bit) 1080ti-card(CUDA8+CUDNN6)     tf-gpu1.3 
then i install dm-sonnet-gpu  ,and run \sonnet\examples\rnn_shakespeare.py , It works on GPU
but run dm-DNC(https://github.com/deepmind/dnc----train.py)  it is error：
An error ocurred while starting the kernel
2017???? 08:37:34.935876: W C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017???? 08:37:35.741301: I C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.721
pciBusID 0000:04:00.0
Total memory: 11.00GiB
Free memory: 10.72GiB
2017???? 08:37:35.741301: I C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0 
2017???? 08:37:35.741301: I C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0: Y 
2017???? 08:37:35.741301: I C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) ?> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0)
2017???? 08:37:42.907917: E C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
2017???? 08:37:42.907917: F C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc:203] Unexpected Event status: 1
2017???? 08:39:55.881633: W C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017???? 08:39:56.474434: I C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.721
pciBusID 0000:04:00.0
Total memory: 11.00GiB
Free memory: 10.72GiB
2017???? 08:39:56.474434: I C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0 
2017???? 08:39:56.474434: I C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0: Y 
2017???? 08:39:56.474434: I C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) ?> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0)
2017???? 08:40:02.511645: E C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
2017???? 08:40:02.511645: F C:\tf_jenkins\home\workspace\nightly?win\M\windows?gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc:203] Unexpected Event status: 1

**Comment by malcolmreynolds** [comment]
@shushan2017 Sorry for the delay - I think this is a TF issue rather than anything Sonnet-specific. This issue looks related: https://github.com/tensorflow/tensorflow/issues/3224 - can you see if the various suggestions there work for you?

**Comment by shushan2017** [comment]
@malcolmreynolds Oh, it doesn't matter. Thank you very much for your attention and answer. I'll go and see.

**Comment by shushan2017** [comment]
After the installation of tf1.5gpu, the operation is normal, it seems to be the problem of TF, but sonnet seems to only need tf1.3 version, I forced the installation of version 1.5.
But the problem seems to come out, the code runs very slowly, 10 times slower than CPU, and the calculations don't seem quite right.

**Comment by malcolmreynolds** [comment]
@shushan2017 as far as I'm aware the most up to date version of TF is 1.4.0rc0 - I'm not aware of any 1.5 branch. You're correct that Sonnet requests the exact version 1.3.0 - we aim to track whatever version of TF is installed by `pip install tensorflow{-gpu}`. When TF 1.4.0 hits stable (ie, there is a non-release-candidate tagged version) we will update Sonnet to make that the supported version. As you've found, if you want to use the current version of Sonnet with a different version of TF you will have to hack things, and the result is unsupported.

It doesn't surprise me too much that the GPU version runs slowly - the DNC architecture is not particularly well suited to GPU, having lots of smaller Tensors that need to be operated on as opposed to larger matrix multiples / convolutions. During development of NTM / DNC we never used GPUs as there seemed to be no benefit to them. A 10x slowdown wouldn't particularly surprise me.

That said, I would expect the answers produced to be the same. When you say calculations "don't quite seem right", can you be more specific?

**Comment by shushan2017** [comment]
@malcolmreynolds Thank you for your answer. I'm concerned about GPU. I want to get higher speed. If DNC isn't suitable for GPU, then I don't bother with it.
About the calculation errors, I just feel sorry, 0.4 is probably remember before the calculation of ACC, and GPU, into 0.003, because the calculation is too slow, I run only once, this information can not explain what. The conclusion is that DNC is really not suitable for running on gpu.

谢谢您的解答，我关注gpu主要想得到更高的速度，如果dnc不适合gpu，那我也就不纠结这个问题了。
关于计算错误，我只是感觉，抱歉，记得之前计算的acc大概是0.4，而用gpu后，变成了0.003，因为计算太慢，我只运行了一次，这个信息完全不能说明什么。得到的结论是dnc的确不适合在gpu上面运行。
再次非常 非常感谢
Thank you for your answer. I'm concerned about GPU. I want to get higher speed. If DNC isn't suitable for GPU, then I don't bother with it.
About the calculation errors, I just feel sorry, 0.4 is probably remember before the calculation of ACC, and GPU, into 0.003, because the calculation is too slow, I run only once, this information can not explain what. The conclusion is that DNC is really not suitable for running on gpu.
Again, thank you very much！！！！！

**Comment by malcolmreynolds** [comment]
@shushan2017 all the results for the Nature paper were done with a Hogwild SGD setup across multiple CPUs (32 cores in some cases) - I'd recommend looking into that for the best performance.
