### ISSUE TITLE
Potentially redundant bias in convLSTM

### ISSUE THREAD

**Issue by lcnature** [deepmind/sonnet#65]
https://github.com/deepmind/sonnet/blob/7da90b8e63fb684b91a12e1e9a42999962804e3a/sonnet/python/modules/gated_rnn.py#L1129

Hi, I realized that the variable of convLSTM includes two biases if `use_bias` is set to true. And I think it is because here the convolution is performed separately on input and state. But effectively only one set of bias is necessary. Perhaps adding bias at the end instead of within the convolution as done in the tensorflow contrib version (https://github.com/tensorflow/tensorflow/pull/8891/files) would be better.

**Comment by malcolmreynolds** [comment]
Fixed as of e15eb742e50044b70e1e4bc008b7598d158786d7 - the old behaviour is still the default as we want to maintain checkpoint compatibility, but setting `legacy_bias_behaviour` to False will apply only one bias.
