### ISSUE TITLE
BatchReshape and BatchFlatten don't work in the straight-forward way

### ISSUE THREAD

**Issue by mingyr** [deepmind/sonnet#70]
Dear engineers, I just want to convert two 4x4 gray images (now the shape is (2, 4, 4, 1)) into some layout suitable for layer normalization ( the intended shape is (2, 16), let's assume here I am sane to do so) and then convert it back. The straight forward way is to utilize BatchFlatten and BatachReshape in pair to do the job. But such a natural idea seems to be not workable here:

```
import tensorflow as tf
import sonnet as snt

class MyLN(snt.AbstractModule):
    def __init__(self, name = "my_ln"):
        super(MyLN, self).__init__(name = name)
        with self._enter_variable_scope():
            self._ln = snt.LayerNorm()

    def _build(self, inputs):
        return snt.BatchReshape(inputs.get_shape().as_list())(self._ln(snt.BatchFlatten()(inputs)))

t = tf.truncated_normal([2, 4, 4, 1])

n = MyLN()(t)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    t_val, n_val = sess.run([t, n])

    print(t_val)
    print(n_val)

```

I just wonder have I misunderstood something about these two modules? Thanks a lot for pointing out that.

**Comment by malcolmreynolds** [comment]
@mingyr BatchReshape takes as input the desired output shape, _without_ the batch dimension (to allow for situations where the batch dimension is unknown at graph construction time. Try the following to strip the batch dimension:

```
    def _build(self, inputs):
        return snt.BatchReshape(inputs.get_shape().as_list()[1:])(self._ln(snt.BatchFlatten()(inputs)))
```

**Comment by mingyr** [comment]
@malcolmreynolds Got it. Yes it is more convenient that the batch dimension is totally put out of consideration. Please feel free to close the thread.
