### ISSUE TITLE
What is the method to load a sonnet model in C++ for inference?

### ISSUE THREAD

**Issue by unitive-jim** [deepmind/sonnet#75]
I just became aware of Sonnet and am considering using it for a project that I am working on, a program to play the card game Hearts using techniques inspired by AlphaGo.

I need to be able to run prediction/inference in C++. I'm currently using TensorFlow's Estimator framework and the SavedModel interface which makes it easy to export a model from python that can be loaded in C++ with just a few lines of code.

From your FAQ, I get the impression that exporting a Sonnet model isn't as simple, and there is no direct support for loading into C++. Yet I imagine you guys do that routinely for many of your projects. Is there support for this in Sonnet now? If not, can you outline how you do it?

**Comment by malcolmreynolds** [comment]
Hi,

Sorry for the delay.

There's nothing specific in Sonnet for conversion to a C++-serveable form, but the underlying data structure created by Sonnet can be saved out as a normal GraphDef / MetaGraphDef. I'm not actually aware of people who use Sonnet doing this regularly - Sonnet is for our research team, and most of the models built with it aren't going directly into production. There have been a few exceptions, I can check if anyone has any more specific guidance, but in the meantime I would recommend looking at the basic TF serving guides, like [this one](https://www.tensorflow.org/serving/serving_basic).

Once the model is built and trained, you export it, providing a signature for the input / output tensors, and you can then serve with the tensorflow_model_server binary or similar.
