### ISSUE TITLE
AttributeError: 'int' object has no attribute 'items'. PTB reader, bayesianrnn.

### ISSUE THREAD

**Issue by gaceladri** [deepmind/sonnet#79]
Hello,

I am having the next issue within the example `brnn_ptb.py`:

```
INFO:tensorflow:Log Directory: /tmp/bayesian_rnn/run1
INFO:tensorflow:Beginning a training phase of 70 epochs.
Traceback (most recent call last):
  File "sonnet_bayesian_rnn.py", line 579, in <module>
    tf.app.run()
  File "/home/proto/anaconda3/envs/sonnet/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "sonnet_bayesian_rnn.py", line 568, in main
    train(logdir)
  File "sonnet_bayesian_rnn.py", line 380, in train
    batch_size=FLAGS.batch_size)
  File "sonnet_bayesian_rnn.py", line 105, in __init__
    self.id2word = {v: k for k, v in self.word2id.items()}
AttributeError: 'int' object has no attribute 'items'
```
Python 3.5, tensorflow 1.5

Before this, I also had to update the ptb_reader to read correctly the documents within python 3. Just copied the ptb_reader from tensorflow example that is up-to-date with it. If you want I can submit a PR to fix this.

Thanks.

**Comment by malcolmreynolds** [comment]
@gaceladri thanks for your report - this is now fixed in version 1.20. You can get the updated version from GitHub master right now, or if you install with `pip` the updated wheels are available now. Please reopen this ticket if you have any problems.
