### ISSUE TITLE
Dependency clarification

### ISSUE THREAD

**Issue by mingyr** [deepmind/sonnet#80]
Dear Deepminder:

I would think it is not a bug, but however I would post here to see whether there is a way for an easy installation.

Usually when compiling TensorFlow manually, even specified with CUDA support, the final binary could NOT reflect such characteristics. Usually this is the file I finally got:
/tmp/tensorflow/tensorflow-1.8.0-cp27-cp27mu-linux_x86_64.whl
Please note I enable GPU support when compiling.

When I installed it with pip, it only reads for example tensorflow is installed instead of tensorflow-gpu

However when I install sonnet with the following instruction:
```
$ mkdir /tmp/sonnet
$ bazel build :install --define gpu=true
$ ./bazel-bin/install /tmp/sonnet
$ pip install /tmp/sonnet/dm_sonnet_gpu-1.20-py2-none-any.whl

```
It will try to download and install the gpu version of TensorFlow, for example tensorflow-gpu-1.8.0.

Since I know the installed tensorflow-gpu-1.8.0 is NOT what I wanted, so I have to uninstall it and  re-install my own's TensorFlow.

But now it always complain:
dm-sonnet-gpu 1.20 requires tensorflow-gpu>=1.0.1, which is not installed.

What I mean is, if I build sonnet from source, could it be a little relaxed on dependency checking? I definitely know the TensorFlow I am gonna install is with GPU enabled, so I just want simply install sonnet and suppress the complains. 

I just wonder can an extra flag be added for the following command, like:

`$ bazel build :install --define gpu=true **dependency-check=false**
`
Or do you know can I configure the generated TensorFlow binary, for example, the generated binary reflects the case GPU has been enabled and hence satisfies the requirement of the GPU version of Sonnet?

Thanks a lot.

**Comment by diegolascasas** [comment]
Hi @mingyr, 
`dm-sonnet-gpu` requires `tensorflow-gpu` as a dependency, but `dm-sonnet` does not. You can generate a `dm-sonnet` wheel if your do not set `gpu` to true, and that should solve your issue. But if you generate a Tensorflow wheel from source using GPU settings, its project name should be `tensorflow-gpu` and it should satisfy the dependency... Is that what you need?

**Comment by diegolascasas** [comment]
Well, if you installed a `tensorflow` wheel you can generate the `gpu=false` sonnet wheel and it should work fine.

I'll close this issue for now, but feel free to reopen it if there is any problem with your installation.

**Comment by mingyr** [comment]
Dear @diegolascasas: 
Does it mean there is no essentially difference between CPU version of sonnet and GPU version of sonnet, isn't it? So in most cases, the two wheels are interchangeable, yes?
