### ISSUE TITLE
found a bug in sonnet/python/modules/baisc/merge_leading_dims

### ISSUE THREAD

**Issue by Burning-Bear** [deepmind/sonnet#81]
https://github.com/deepmind/sonnet/blob/c838ebfca0623d2855d87fac65dce225573a4628/sonnet/python/modules/basic.py#L77
the parameter 'keepdims' in tf.reduce_prod has changed to 'keep_dims' at least in tensorflow >=1.4.0.

**Comment by malcolmreynolds** [comment]
HI @Burning-Bear 

In the latest version of TF, `keepdims` is the correct kwarg name. `keep_dims` was the old name, which is still available but deprecated - see https://www.tensorflow.org/api_docs/python/tf/reduce_prod

In general we develop Sonnet against the newest public release of TensorFlow only, so while most of it will work with older versions it is not guaranteed. If you are unable to upgrade your version of TF for whatever reason, the best option is to use a correspondingly old version of Sonnet - you can check this here https://github.com/deepmind/sonnet/blob/master/CHANGES.md - in your case, Sonnet 1.14 should fully support TF 1.4.0. I would recommend using the latest stable versions of TF & Sonnet if at all possible though.

**Comment by Burning-Bear** [comment]
Thanks, I get it! sorry for my mistake. :)
