### ISSUE TITLE
keepdims=True

### ISSUE THREAD

**Issue by arvind-cp** [deepmind/sonnet#85]
Hello,

There is a minor bug in /sonnet/python/modules/nets/vqvae.py 
Please change keepdims=True to keep_dims=True
The underscore is missing and it fails for TF ver 1.4 

Also it looks like the VAE example wasn't run on python3 because of the way you import cPickle. But main sonnet readme says that python3 is supported. 
For python3, this will work:
import _pickle as cPickle

Thanks,
Arvind

**Comment by diegolascasas** [comment]
Hi Arvind,

Thank you for your feedback!

`keep_dims` is deprecated in the latest version of Tensorflow. See answer to issue  #81.

Sonnet should be 100% python3 compatible, this `cPickle` import slipped through us.
We'll address the mistake and update this issue when the changes are pushed.

**Comment by diegolascasas** [comment]
Hi @arvind-cp,

We just released a new version that fixes the Python 3 compatibility problems.
It will soon be in PyPI as well.

I'll close this issue, but feel free to reopen it if you spot anything else.
