### ISSUE TITLE
multi GPU batchsize problem

### ISSUE THREAD

**Issue by skyuniversee** [deepmind/sonnet#94]
How can i build a multi-gpu model using sonnet?
i have tried this:

```python
model = i3d.InceptionI3d(
            400, spatial_squeeze=True, final_endpoint='Logits', name='inception_i3d')
for i in range(0, _GPU_NUM):
  with tf.device('/gpu:%d' % i):
    with tf.name_scope('tower_%d' % i) as scope:
      logits, _ = model(clip_split[counter], is_training=is_train_holder, dropout_keep_prob=dropout_holder)
```

the first line is to call the constructor, the 6th line call the build method.It can work for multi-gpu, but the problem is that it cant expand the batch_size. When I use single gpu, the largest batchsize gpu can afford is 4. And it doesnt change when i use multi gpu ,causing it failing to accelerate the train.Could anyone help me how I can build Multi-gpu model using sonnet?

**Comment by diegolascasas** [comment]
I'm sorry, I'm not sure I understand your question. 
How are you creating clip_split? What is it's shape?

**Comment by tomhennigan** [comment]
Closing out some old issues, please reopen if this is still a blocker.
