### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by EliasHasle** [deepmind/sonnet#96]
Sonnet seems like a great library, but the web page is not so great. It would help to have a few _complete_, super-simple examples that don't showcase what fancy stuff Sonnet does easier/better than other solutions, but just shows how to get started. Even if that involves repeating some "obvious" TensorFlow code. (Right now one of my questions is when I will have to use pure TF and when Sonnet provides a shorthand.)

Of course, what would be even better would be a browsable documentation page with specification of all functions, classes etc.

Personally, as a newbie in ML, even though I am a big fan of Deepmind and would like to use Sonnet, so far Keras has proven to be the simple place to start, exactly because of relatively good documentation and tutorials. I am sure I will overcome the initial difficulties rather soon, but if it is your intention to simplify working with neural networks, I challenge you to make Sonnet the natural starting point for beginners.

**Comment by diegolascasas** [comment]
Hi @EliasHasle, thanks for the feedback!

We are planning a revamp in the documentation, and will take your input into account.
We can come up with a couple of iPython notebooks that showcases some of Sonnet's functionalities.

**Comment by d04922013** [comment]
Any planned schedule?

**Comment by EliasHasle** [comment]
I noticed that there are now overviews of the modules etc. linked at the bottom of the documentation page at the github.io site, (but not in the corresponding md file in docs here). I don't know if it was there when I posted this issue, but having it there is a start. The modules page is not exactly an easy-reader, though.

**Comment by EliasHasle** [comment]
Closing after recent improvements to docs. Thumbs up!
