### ISSUE TITLE
Reproducing Cifar-10 results for VQ-VAE

### ISSUE THREAD

**Issue by shihux** [deepmind/sonnet#98]
Hi, 

I am trying to reproduce the likelihood lower bound results for Cifar-10 mentioned in Section 4.1 of the "Neural Discrete Representation Learning" paper. There are a few questions I hope you could answer:

1. Section 4.1 of the paper mentions all residual blocks have 256 hidden units. I am assuming this means there are 256 output channels out of a residual block (from the "residual_stack" function). However, at the bottom of Section 3.2 it says the latent dimension for Cifar-10 is 8 x 8 x 10. Does it mean the last residual block outputs a feature map with number of channels 10 instead of 256?

2. Section 3.2 defines the variational lower bound as p(z_q(x)) log[p(x | z_q(x))]. However, it is unclear how to compute log[p(x | z_q(x))]. The loss function uses MSE instead of the actual log-likelihood.

Thanks!

**Comment by malcolmreynolds** [comment]
Hi @shihux,

I will pass these questions on to the authors of the VQ-VAE paper.

**Comment by tomhennigan** [comment]
Closing out some old issues, please reopen if this is still a blocker.
